### ISSUE TITLE
Example for horizontal scrolling ? 

### ISSUE THREAD

**Issue by thecritic** [orizens/ngx-infinite-scroll#105]
I'd love to have an example or documentation on horizontal scrolling. As far as I know (looking through the issues) there has already been a PR regarding this feature and maybe somebody can quickly write up an example usage scenario without me looking into the code extensively, that would be really appreciated. 

This has been a really helpful module to me, hopefully somebody can guide me through the horizontal part, that would make it even better. Thanks a lot.

**Comment by orizens** [comment]
@emeyekayee - you were the one to add this feature (if i'm not mistaken).
do you have an example to share?

**Comment by Reece387** [comment]
I am using the horizontal scrolling on my web app and it works and although I want to share... my code is buggy currently as I am trying to cater to mobile users and be able to switch from horizontal to vertical scrolling and vice versa as they switch from portrait to landscape mode so I am currently working on that.

If you want to take a look at it, it is in my home component over at [diadoz-1.0](https://github.com/DIADOZ/diadoz-1.0)

**Comment by fettunch** [comment]
Hi all,

I have some trouble making the horizontal scroll working in my angular app.


alert.component.css:

.notifiContent{
    overflow: scroll;
    max-height: 150px;
    table{table-layout:fixed;}
    td{
        white-space:nowrap;
        text-align: center;
    }

**Comment by fettunch** [comment]
Hi, I see some experts in this thread and I have been checking for the past days but unfortunately I could not find a way to get the horizontal scroll working...is there anyone able to help me? :)

**Comment by emeyekayee** [comment]
Hi Fabio,

Well, it's been awhile but as I recall the element to which you apply
the InfiniteScroll directive also needs to have a 'horizontal=true'
attribute.  My example looks something like this:

  template: `
    <div class="timespans-container">
      <div class="scrolling-container"
           ...
           infinite-scroll
           [horizontal]="true"
           ...
           >

        ...

      </div>
    </div>
  `

And if I recall correctly, setting the style/css works better
as 'overflow-x: scroll;' than as just 'overflow: scroll;'

Hope that helps, and be well!
 - Mike
