### ISSUE TITLE
Infinite onScroll callback on just single scroll

### ISSUE THREAD

**Issue by ak0arjun** [orizens/ngx-infinite-scroll#106]
Hi,

I followed the example https://plnkr.co/edit/DrEDetYnZkFxR7OWWrxS?p=preview and implemented demo angular2 app, the app i created in that on doing single scroll on window calls onScroll callback too many times, for the sampe app plunker example works fine.

I am attaching my demo code could you please help me to find the error in my code?

My app component file
import {Component} from '@angular/core'

@Component({
  selector: 'my-app',
  styles: [`
    
    .title {
      position: fixed;
      top: 0;
      left: 0;
      background-color: rgba(0,0,0,.5);
      color: white;
      width: 100%;
    }
    .title small {
      color: #eaeaea;
    }
  `],
  template: `
    <h1 class="title well">{{ title }} <small>items: {{sum}}</small></h1>
    <div class="search-results"
         infinite-scroll
         [infiniteScrollDistance]="scrollDistance"
         [infiniteScrollThrottle]="throttle"
         (scrolled)="onScrollDown()">
      <p *ngFor="let i of array">
        {{ i }}
      </p>
    </div>
  `
})
export class AppComponent {
  array = [];
  sum = 100;
  throttle = 500;
  scrollDistance = 1;
  title = 'Hello InfiniteScroll v0.2.8, Ng2 Final';

  constructor() {
    this.addItems(0, this.sum)
  }
  
  addItems(startIndex, endIndex) {
    for (let i = 0; i < this.sum; ++i) {
      this.array.push([i, ' ', this.generateWord()].join(''));
    }
  }
  onScrollDown () {
    console.log('scrolled!!');

    // add another 20 items
    const start = this.sum;
    this.sum += 20;
    this.addItems(start, this.sum);
  }
  
  generateWord() {
    return "test";
  }
}

[demo.zip](https://github.com/orizens/angular2-infinite-scroll/files/677176/demo.zip)

**Comment by orizens** [comment]
hi.
please share this code as a plunkr

**Comment by kim-cph** [comment]
missing the <!DOCTYPE html> in index.html . 

seems also missing the  style
.search-results {
      height: 100%;  
    }
but not sure if needed .

https://github.com/orizens/angular2-infinite-scroll/issues/7

**Comment by kevinphelps** [comment]
I denounced the scroll event in my app to help correct this.

**Comment by SirWojtek** [comment]
@kim-cph You made my day, mate. I was struggling with scroll frequency for almost an hour. Indeed, adding `DOCTYPE` resolves that problem for me.

**Comment by kamal0912** [comment]
> I denounced the scroll event in my app to help correct this.

Hi @kevinphelps , I am facing this same annoying issue. Can you please share how have you implemented Debounce?

**Comment by kevinphelps** [comment]
O just used the RxJS `debounce` operator.

**Comment by kamal0912** [comment]
> I just used the RxJS `debounceTime` operator.

Thankyou @kevinphelps  for quick reply. Following is my scrolldown function:

onScrollDown(e) {
        this.getBatchDetails();
    }

Can you tell me how should I implement debounceTime operator in this function? I would really appreciate the help.
