### ISSUE TITLE
Any known issues with Android stock browser?

### ISSUE THREAD

**Issue by manugarciac** [orizens/ngx-infinite-scroll#123]
Your infinite scroll is working flawlessly with Chrome, but not working at all when I load my app with Android stock browser.

**Comment by orizens** [comment]
isn't chrome the default browser as of android 5 or 6?

**Comment by manugarciac** [comment]
I'm not sure, but what if someone is using an older version? In fact, we were testing it and someone was using that browser without knowing.

**Comment by orizens** [comment]
that's out of of scope for this module - as it is a part of a framework.

**Comment by manugarciac** [comment]
But it's expected not to work then? I want to make sure I'm not doing something wrong.

**Comment by orizens** [comment]
I have no way of testing it in Android Stock Browser.

**Comment by manugarciac** [comment]
Ok. Maybe someone who reads this can try it. I'll prepare a simple example to make sure I'm doing everything right.

**Comment by manugarciac** [comment]
I debugged it and made it work. I changed the following line in scroller.js:

`this.isContainerWindow = Object.prototype.toString.call(this.windowElement).includes('Window');`

To

`this.isContainerWindow = true;`

And it seems to work well. Of course, I have no idea what that may be breaking elsewhere. Do you know why that is there?

**Comment by orizens** [comment]
this value is crucial for setting the listener for regular container or listening to the window's scroll event.
can you please share the value of: 
1. Object.prototype.toString.call(this.windowElement)
2. Object.prototype.toString.call(this.windowElement).includes('Window') 

perhaps one of this results in null or undefined.

**Comment by manugarciac** [comment]
Ok. I did just that an these were the results:

1. [object global]
2. false

**Comment by manugarciac** [comment]
HI again. Just wanted to let you that right now I have it like this (position-resolver.js):

```
    PositionResolver.prototype.resolveContainer = function (windowElement) {
        var isContainerWindow = Object.prototype.toString.call(windowElement).includes('Window') || Object.prototype.toString.call(windowElement).includes('global');
        this.isContainerWindow = isContainerWindow;
        return isContainerWindow;
    };
```

I added `|| Object.prototype.toString.call(windowElement).includes('global')`. It seems to work, but I don't know if it's the correct fix.

**Comment by orizens** [comment]
i have no way of testing this.
