### ISSUE TITLE
IE11 scrollup bug

### ISSUE THREAD

**Issue by stotzout** [orizens/ngx-infinite-scroll#144]
I'm trying to get this plnkr running on IE11.

https://plnkr.co/edit/n7iqb2Ugv6tQv1DF2SX2?p=preview

The reload on scrolling works fine. But if i'm scrolling up, the scroll button doesn't went down like in chrome browser.

Is it a known issue? And is it fixable?

**Comment by orizens** [comment]
@stotzout the plunkr seems to be working fine. anything i'm missing?
