### ISSUE TITLE
Put Deprecation Notice in README 

### ISSUE THREAD

**Issue by jcroll** [orizens/ngx-infinite-scroll#150]

**Comment by jcroll** [comment]
There is a link on npm saying this is a different repo (`github.com/orizens/angular2-infinite-scroll`) but redirecting to this repo, which is why I am confused.

This is the source of the confusion:

![angular2 infinite scroll](https://cloud.githubusercontent.com/assets/1441013/25138316/35f2f390-2428-11e7-9f6f-7cb9d9731225.png)

**Comment by orizens** [comment]
hi @jcroll 
you are right - I apologize for the confusion - i renamed the repo to be "ngx-infinite-scroll", so the "angular2-infinite-scroll" link redirects to the new link.

**Comment by jcroll** [comment]
Thanks @orizens 👍
