### ISSUE TITLE
Strange symbols in your index.d.ts.

### ISSUE THREAD

**Issue by cdibbs** [orizens/ngx-infinite-scroll#155]
When I install your library, I get an index.d.ts with the following:

```typescript
/**
 * Generated bundle index. Do not edit.
 */
export * from './public_api';
export { InfiniteScrollDirective as ɵa } from './src/modules/infinite-scroll.directive';
export { AxisResolverFactory as ɵc } from './src/services/axis-resolver';
export { PositionResolverFactory as ɵb } from './src/services/position-resolver';
export { ScrollRegister as ɵd } from './src/services/scroll-register';
export { ScrollResolver as ɵe } from './src/services/scroll-resolver';
```

That seems to prevent me from importing anything other than InfiniteScrollModule (which is in public_api). Notice how all the exports have been renamed. I think you want those exports in public_api.ts. I'm not sure the root index.ts is even needed? At least, that's what works for me.

Sidenote: someone has to organize all this nonsense. It's really too bad ng cli doesn't support creating a standard library starter.

**Comment by orizens** [comment]
hi @cdibbs 
currently, only the module is exported.
this index.d.ts is generated via the starter kit that i chose to use for this component.
You should not use the other objects yet.
