### ISSUE TITLE
Wrong scroll direction on container initialisation or reload leads to fast scroll event being lost

### ISSUE THREAD

**Issue by renehamburger** [orizens/ngx-infinite-scroll#159]
Under certain condition, your InfiniteScroll directive interprets an initial downwards scroll as an upwards scroll. When the following downward scroll is then done within the throttling time, it will not emit the scroll event at all, as `scrollStats === {isScrollingDown: false, shouldScroll: false}`.

You should be able to reproduce this in your [modal plunkr](https://plnkr.co/edit/QnQOwE9SEapwJCCFII3L?p=preview) as follows:
- reduce the window height to about 500px
- open the modal
- scroll the scroll bar in the modal down as far as possible
- close the modal
- scroll the page down

For me, this always triggers an upwards scroll event.

Our setup is somewhat different. In two cases, your directive registers an initial upwards scroll without the user having scrolled up:
1. On a reload of an infinite list that is already scrolled down a bit. During the reload, the list is temporarily emptied so that the scroll bar disappears. When that happens, an upwards scroll event is triggered.
2. During the initialisation of a infinite list in a modal, with a scroll bar appearing and disappearing in the init process. When the user then scrolls down, an upward scroll event is triggered.

**Comment by mm-pw2016** [comment]
+1

I've also been experiencing this issue. Despite the throttle being set to 0, the first one, (sometimes two? maybe depends on screen size) scrollDown event may debounce the execution by ~3 seconds.
Funnily enough, I've noticed that Firefox doesn't seem to propagate this behaviour, even though it's constant on Chrome.

**Comment by orizens** [comment]
hi @renehamburger 
can you propose a PR for this?

**Comment by orizens** [comment]
does this still happen?

**Comment by orizens** [comment]
hi @renehamburger  please try the latest 0.8.0 and let me know.
