### ISSUE TITLE
Trigger event when reach the bottom of page

### ISSUE THREAD

**Issue by cuongnm265** [orizens/ngx-infinite-scroll#161]
How can I make the event is only trigger when its reach the bottom of the page? Thank you

**Comment by leoxgnr93** [comment]
@cuongnm265  Hi!
Did you solve it?
If so, I'm dealing with the same thing.
Hope you can help 
Thanks

**Comment by cuongnm265** [comment]
@leoxgnr93 In the documentation:
`infiniteScrollDistance<number> - (optional, default: 2) - should get a number, the number of viewport lengths from the bottom of the page at which the event will be triggered.`
=> I set `infiniteScrollDistance` to 0 mean 0 viewport from the bottom of the page to the event trigger

**Comment by vietduong-agilityio** [comment]
@cuongn265 Can you help to provide config for this, I set `[infiniteScrollDistance]="0"` but it not work :(

**Comment by kirstenfrager** [comment]
@vietduong-agilityio did manage to solve this? facing some issue
