### ISSUE TITLE
Using infinite scroll on a typeahead-container?

### ISSUE THREAD

**Issue by atbe** [orizens/ngx-infinite-scroll#165]
Hi,

Currently I have an Angular component that is using the angular2 typeahead to generate an `ul` of options the user can choose from.

I wanted to make that `ul` scrollable while enabling virtualization using paging, so that's where `ngx-infinite-scroll`.

I'm not sure how to get the infinite-scroll directive to target the `ul` because it is generated on the fly by the typeahead directive.

Here is what the components HTML looks like:

```
<div class="search-results"
	 infinite-scroll
	 [infiniteScrollDistance]="2"
	 [infiniteScrollThrottle]="300"
	 (scrolled)="onScroll()">

	<input name="account"
		   [(ngModel)]="searchText"
		   (ngModelChange)="updateLineitem()"
		   [typeahead]="accountData"
		   (typeaheadOnSelect)="onAccountSelected($event)"
		   typeaheadOptionField="customName"
		   typeaheadMinLength="0"
		   typeaheadWaitMs="75"
		   autocomplete="off"
		   placeholder="Select an Account"
		   class="form-control lookupWidth">
</div>
```

Has anyone been able to use `typeahead` and infinite-scroll in harmony? I know there is a `infiniteScrollContainer` attribute but I cannot find the correct `ElementRef` to use.

The html looks like this when the typeahead kicks in:

https://pastebin.com/pwrVeqaV

Thanks!

**Comment by orizens** [comment]
hi @atbe 
I would try to set ```scrollWindow ="false"```so the scroll event is attached to the "search-results" container and not to the window.

**Comment by atbe** [comment]
@orizens thanks for the quick response. I have tried that already but forgot to put it back in.

The real issue is what the value should be for `infiniteScrollContainer`? It seems like the infinite-scroll will not attach to the `ul` because it is not a direct child.

**Comment by orizens** [comment]
yes - that's right - i missed that.
however - you might be able to achieve that using custom Template for the if you use ngx-typeahead instead.

**Comment by atbe** [comment]
@orizens `ngx-typeahead` works similar to what the built in `typeahead` is doing, it looks like. It is still lacking the feature that `infinite-scroll` provides which is:

`pagination when the user scrolls to the bottom of the typeahead search results`.

So in essence the need is to be able to change the content which is being presented by the typeahead through scrolling and minimizing the number items in the list that need to be rendered (internet explorer starts to blow up when the list is size >300).

If `ngx-typahead` also supported infinite scroll, it would be the key. But looking at the page [here](https://www.npmjs.com/package/ngx-typeahead) and the plunker that is included, it is still only showing a fixed number of completions (10) and doesn't allow the user to scroll beyond those 10 results to see the remaining matches.

**Comment by orizens** [comment]
yes - you would need to develop this feature - as it is not part of its functionalities.
