### ISSUE TITLE
Scroll does not work when parent height is set to 100%

### ISSUE THREAD

**Issue by zishanj** [orizens/ngx-infinite-scroll#168]
I am using Angular Material component `md-sidenav` and have wrapped the scrollable content inside `md-sidenav-container` which is the parent tag. For `md-sidenav-container` we have a criteria to set its height to 100% to fully display the nav list on entire page. If we set this to 100% then infinite-scroll does not work on its child scrollable content which is `md-list` Material component, if we remove this 100% height then it works.

Is there any workaround to this?

**Comment by orizens** [comment]
100% works with http://echoesplayer.com

**Comment by orizens** [comment]
please consult this issue for possible solution
https://github.com/orizens/ngx-infinite-scroll/issues/98
