### ISSUE TITLE
implement `infinite-scroll-disabled` and `infinite-scroll-listen-for-event`

### ISSUE THREAD

**Issue by marcalj** [orizens/ngx-infinite-scroll#17]
I would love to help implementing this but I'm opening the issue as a reminder.

Thanks!

**Comment by orizens** [comment]
hi @marcalj ,
These seems to be a logic oriented features that should be handled in services.

**Comment by marcalj** [comment]
Makes sense, thanks.

**Comment by marcalj** [comment]
Hmmm, not so quickly.
I was using `infinite-scroll-listen-for-event` to say "hey, if the DOM element is at the bottom, trigger the next page event". So, it's useful because this directive knows if it should trigger the event or not.

**Comment by marcalj** [comment]
Also I was using `infinite-scroll-disabled` to gain performance and disable checks when no one is listening. I think it worth it.

**Comment by orizens** [comment]
still - it looks like it belongs in logics. 
lets wait for others to vote for it.

**Comment by zoehneto** [comment]
I would be interested in infinite-scroll-disabled so I can stop the evaluation if I'm already loading the next set of data.

**Comment by orizens** [comment]
@zoehneto , 
i'm just taking a note for the implementation - as now, the window scroll event is implemented with [rxjs functions](https://github.com/orizens/angular2-infinite-scroll/blob/master/src/scroller.ts#L140). it sounds like it can be integrated to this flow, though another handler should be implemented if the @HostListener is invoked on the actual DOM element rather than the window.

**Comment by marcalj** [comment]
@orizens How can I check if the infinite scroll event should be triggered outside the component? I think I can't access this information and I cannot implemented in my business code. Thanks!

**Comment by orizens** [comment]
hi @marcalj 
I havn't tried it - however, you can access the directive instance with [@ViewChildren](https://angular.io/docs/ts/latest/api/core/index/ViewChildren-var.html) or [@ViewChild](https://angular.io/docs/ts/latest/api/core/index/ViewChild-var.html)
and then, trigger on the scroller property the "clean()" function for removing the scroll. for re-attaching the behavior, use the "defineContainer()" function. 
This should work for a "window" listener only.
