### ISSUE TITLE
Issue with AoT Angular 4

### ISSUE THREAD

**Issue by lukasasorensen** [orizens/ngx-infinite-scroll#171]
Error: Unexpected value 'InfiniteScrollModule' imported by the module 'AppModule'. Please add a @NgModule annotation.

src/app/App.module.ts
@NgModule({
	imports: [
        SharedModule.forRoot(),
        FormsModule,
        ReactiveFormsModule,
        HttpModule,
        TransferHttpModule,
        InfiniteScrollModule,
        NgReduxModule,
        MdToolbarModule,
        MdIconModule,
        MdMenuModule,
        MdTabsModule,
        MdSnackBarModule,
        MdInputModule,
        MdButtonModule,
        MdSelectModule,
        DialogModule.forRoot([LoginForm, SignupComponent, ResetComponent]),
        CardModule,
        TabsModule,
        FilterDropdownModule,
        AuthModule,
        RouterModule.forRoot(AppRoutes)
	],
    providers: [
        AuthenticationService,
        AuthGuard,
        DialogService,
        IdentityService,
        StorageService,
        UserService,
        ToasterService,
        LiveAnnouncer,
        PollingService,
        FacebookService
    ],
    declarations: [
        AppComponent,
        HomeView,
        HeaderComponent,
        FooterComponent,
        NavBarComponent,
        LoginForm,
        SignupComponent,
        ResetComponent
    ],
    exports: [ AppComponent ],
    bootstrap : [ AppComponent ]
})
export class AppModule {
    constructor(private _facebookService: FacebookService) {
        let initParams: InitParams = {
            appId: Config.facebookAuth.clientId,
            xfbml: true,
            version: 'v2.9'
        };
        //initialize and setup the SDK
        this._facebookService.init(initParams);
    }
}

**Comment by orizens** [comment]
make sure your build process extracts the correct file for inifinite-scroller
