### ISSUE TITLE
ngx-infinite-scroll/index"' has no exported member 'InfiniteScroll'

### ISSUE THREAD

**Issue by MvS-IT** [orizens/ngx-infinite-scroll#177]
Hi, I installed ngx-infinite-scroll through npm; followed the usage instructions, but after an ng serve I see this message:
ngx-infinite-scroll/index"' has no exported member 'InfiniteScroll'
Any suggestions would be welcome.
Cheers Marnix

**Comment by orizens** [comment]
you should import "InfiniteScrollModule" only.
which ng version are you using?
can you share a repo?

**Comment by MvS-IT** [comment]
I added the InfiniteScrollModule in the main app module, but after putting it in a sub feature module it works. 
By the way, I work with Angular 4.0.3 and webpack
Can be closed

**Comment by bruteforce** [comment]
@MvS-IT  "but after putting it in a sub feature module it works." Same with me.

**Comment by shirishpickup** [comment]
I face the same issue.
Scroll methods are being called, but when i do the below
import { InfiniteScroll } from 'ngx-infinite-scroll';
compiler throws an error saying "...module has no exported member InfiniteScroll"

Any help ?

**Comment by amardeepthadisetty** [comment]
I am also getthing this error : 
Module '"...angular/node_modules/ngx-infinite-scroll/ngx-infinite-scroll"' has no exported member 'InfiniteScroll'.


I have imported this in my module : 
import { InfiniteScrollModule } from 'ngx-infinite-scroll';

When in my view, putting these things to a div
infiniteScroll
				[infiniteScrollDistance]="2"
				[infiniteScrollThrottle]="50"
				(scrolled)="onScroll()"

page is not showing up at all.

So in that cmponent i added : import { InfiniteScroll } from 'ngx-infinite-scroll';
then the app crashes gives me : ngx-infinite-scroll has no exported member.

Help appreciated!!!

**Comment by JianlingLuo** [comment]
i have the same problem

**Comment by mydaypower1** [comment]
has no exported member 'InfiniteScroll'

I have the same problem

**Comment by Luarb** [comment]
use this : 
`import { InfiniteScrollDirective } from 'ngx-infinite-scroll';
`
