### ISSUE TITLE
Jasmine testing TIMEOUT

### ISSUE THREAD

**Issue by mkonicki94** [orizens/ngx-infinite-scroll#180]
Hi guys 
I encounter on exception with unit testing with Jasmine.
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

It occurs, when component is create with fixture, and I called method detectChanges(). 
asmine throw timeout, without call that method everything pass.
Later I will add code to full reproduce that.

**Comment by orizens** [comment]
please share a repo/plunkr with this issue.

**Comment by orizens** [comment]
closed - lack of info.

**Comment by ednjv** [comment]
I'm having this exact problem. Were you able to solve it?

**Comment by ednjv** [comment]
Ok as @mkonicki94 points out, removing the `detectChanges` method after the component has been created seems to solve this for me too. I can't do a research right now why this happens, but for now this works, thanks
