### ISSUE TITLE
Scroll doesn't work on the Standard Android browser

### ISSUE THREAD

**Issue by volodymyro-in6k** [orizens/ngx-infinite-scroll#181]
Hello, thank you for your contribution. It's really amazing!
I'm trying to test it with different devices.
So I have found the issue on the Xioami Mi Max (Android 6.0.1, Standart Browser V7.7.4). 
With Chrome all work fine. 

On this device, all work fine Xiaomi Redmi 3 (Android 5.1.1, Standart browser V8.9.5)

It seems like the problem could be with the browser version and may be there is some issue but in any way it is.

Thanks!

**Comment by orizens** [comment]
hi @volodymyro-in6k 
i don't have any way of testing this one.
android browser is currently out of scope - unless you can suggest a pr for that.
Thanks.

**Comment by orizens** [comment]
there was a suggested fix on https://github.com/orizens/ngx-infinite-scroll/issues/123#issuecomment-292529234
but i have no way to verify this.
