### ISSUE TITLE
Many requests canceled by chrome

### ISSUE THREAD

**Issue by kevincaradant** [orizens/ngx-infinite-scroll#183]
Hi

I have a little problem about some requests canceled by chrome browser. In fact, my request takes around 700ms, so I need to write [infiniteScrollThrottle]="700" to avoid a cancel request but it's really annoying about performance for the end user.

Do you know what advice do I need to queue all requests asked and never cancel one ? 

Thank you in advance.

Regards 

![image](https://user-images.githubusercontent.com/6093175/29562058-201dc5fe-8738-11e7-9dc2-3502c545436b.png)

This is my snippet:

```
<div infiniteScroll [infiniteScrollDistance]="1" [infiniteScrollThrottle]="700" infiniteScrollContainer=".display-list-users-component" [scrollWindow]="false" (scrolled)="onScroll()">
```

NB: I don't want use [infiniteScrollThrottle]="700"  which is just a really bad workaround and if the connexion is bad, I will have again some canceled requests.

**Comment by orizens** [comment]
hi.
it's not related to this component.
this is rather a logics design decision.
