### ISSUE TITLE
throttle should throttle not delay.

### ISSUE THREAD

**Issue by cedvdb** [orizens/ngx-infinite-scroll#184]
A throttle of 400 does this at the moment when events have been fired at 0ms, 200ms, 400ms

(top line is real events, bottom line is events emitted by infinite-scroll
```
e---e---e
----e----
```
It should do this:

```
e---e---e
e-------e
```

I don't think anyone wants to have a lower response time in his app. The use of throttle is to not fire two events too rapidly.

In Rxjs terms: `throttle` should be used instead of `sampleTime` .

```
@Injectable()
export class ScrollRegister {
  attachEvent (options: IScrollRegisterConfig): Subscription {
    const scroller$: Subscription = Observable.fromEvent(options.container, 'scroll')
      .throttle(v => Observable.interval(options.throttleDuration))
      .filter(options.filterBefore)
      .mergeMap((ev: any) => Observable.of(options.mergeMap(ev)))
      .subscribe(options.scrollHandler);
    return scroller$;
  }
}
```

**Comment by orizens** [comment]
proposed fix doesn't fix it.
thanks.
