### ISSUE TITLE
Callback triggers as soon as I scroll

### ISSUE THREAD

**Issue by houmanka** [orizens/ngx-infinite-scroll#189]
Hi,

I use: Angular 4, Here is what I use for the ngx-infinite-scroll . As soon as I scroll from the top of the page, call back get triggered. 

```
<app-document-search
 infinite-scroll
debounce
[infiniteScrollDistance]="0"
[infiniteScrollThrottle]="300"
 (scrolled)="onScrollDown()"      
[immediateCheck]="false"                       
></app-document-search>
```      

This is embedded inside another component ( document-list-compoenet )
In the document-list-component I put css for height:100% ( wrapped around the  app-document-search )

Can you please help?

**Comment by SirWojtek** [comment]
#106 ?

**Comment by orizens** [comment]
https://github.com/orizens/ngx-infinite-scroll/issues/106#issuecomment-332156857
