### ISSUE TITLE
Problem after updating to 0.6.1

### ISSUE THREAD

**Issue by WiseBird** [orizens/ngx-infinite-scroll#199]
In 0.6.1 version new option was added - `fromRoot` that is false by default. I believe its breaking change, because previously container was resolved from window.
If you do not want to change default to true, please, consider providing helpful error message if container is not found, because now in such case `createResolverWithContainer` is simply throws by calling `nativeElement` on undefined:

```
export function createResolverWithContainer(
  resolver,
  windowElement: ContainerRef
) {
  const container =
    resolver.isWindow || (windowElement && !windowElement.nativeElement)
      ? windowElement
      : windowElement.nativeElement;
  return { ...resolver, container };
}
```

**Comment by orizens** [comment]
@WiseBird 
you're right - it's breaking change - however, resolving the container via a string selector produced bugs.
you're right about the helpful error message - i encourage you to open a pr if you can.
thanks.
