### ISSUE TITLE
Scroll down function is getting called multiple times on scrolling down

### ISSUE THREAD

**Issue by khanna-912** [orizens/ngx-infinite-scroll#200]
Scroll down function gets called multiple time on scrolling down. It should be called just once on scrolling down each time.

**Comment by miro-orpheus** [comment]
I have same problem. If I scroll down scrolled is triggered multiple times (scroll is not to bottom of the page). 
My code is this.
`<div class="timeline"
         infiniteScroll 
         [infiniteScrollDistance]="1"
          [infiniteScrollThrottle]="300"
           (scrolled)="getTimelineData()"
           >
                <app-timeline-day-box *ngFor="let event of timeline;" [event ]="event "></app-timeline-day-box>
        </div>`

**Comment by FilipeQ** [comment]
this happens on scroll down and up

**Comment by miro-orpheus** [comment]
@FilipeQ  on scroll down.

**Comment by miro-orpheus** [comment]
I fixed  this problem with adding "infiniteScrollDisabled".  Now my  code is:
`<div class="timeline" infiniteScroll [infiniteScrollDistance]="1" [infiniteScrollThrottle]="1500" [infiniteScrollDisabled]="blockInfiniteScroll" (scrolled)="getTimelineData()" >
 <app-timeline-day-box *ngFor="let event of timeline;" [event ]="event "></app-timeline-day-box> </div>
`

**Comment by byrenx** [comment]
I've encountered also with the same issue, it continue to call scroll function even if I just scroll down once. This happens when I insert DFP ad banner from google as an item in my list view. But, when I remove the ads in the template it works fine. I don't know if it has something to do with the iframe that google ads added to the template?

**Comment by ebakke** [comment]
Here's what I'm seeing.

Any short/slow scrolling towards the end of the window will trigger multiple `scrolled ` events. Even if the user doesn't start/stop scrolling (by lifting the finger from a trackpad, for example) but just continues scrolling at a slow rate. `scrolled ` will be fired once every `infiniteScrollThrottle` milliseconds until the first call to get more results has completed and the new items have been rendered on the page.

This can also happen if a user keeps hitting/bouncing against the bottom of the page while a page of results are fetched.

It seems that the event should only be triggered once per `container.totalToScroll`. If that hasn't changed, the event should not be triggered again.

**Comment by orizens** [comment]
@ebakke you're right. 
an enhancement of triggering once until totalToScroll has change is the way.

**Comment by orizens** [comment]
fixed by 269b5f6dd84125698620ffce8f0f8b4b1a1bafe5

**Comment by kamal0912** [comment]
> fixed by [269b5f6](https://github.com/orizens/ngx-infinite-scroll/commit/269b5f6dd84125698620ffce8f0f8b4b1a1bafe5)

Hi @orizens , Can you please specify what exactly do I need to write in my code to fix this issue? You have marked this issue as closed, but I am unable to see any solution for it. If I scroll fast, scroll event fires multiple times and this is causing huge problem for me as every scroll down call makes a request to server. Event should get called once the user is done with scrolling. Please help.

**Comment by evavranici** [comment]
I am facing the same issue. It can not seem to be working. Can you give a hint what can be done to get it running propertly (1load per scroll)?

**Comment by aakash-p-27** [comment]
Hey, I am also facing the same issue. Can you please suggest to me what can be done to running properly?

**Comment by TGihan** [comment]
i am also having the same issue. Its duplicating items in my list and send multiple requests to the server. How to prevent multiple scroll event trigger?

**Comment by angularui06** [comment]
I got the same issue and fixed using **infiniteScrollDisabled** (Angular 6)

Html
-------------------------------

<div
      [ngClass]="{'search-results': transactionRows?.length > 0}"
      infiniteScroll
      [infiniteScrollDistance]="2"
      [infiniteScrollThrottle]="50"
      [scrollWindow]="false"
      **[infiniteScrollDisabled]="busyGettingData"**
      (scrolled)="onScroll()"
    > Table Code </div>

TS
------------------------------------------------

busyGettingData = false;

  onScroll() {
    if (this.busyGettingData) {
      return
    }
    this.busyGettingData = true
  this.getAPIData();
  }

getAPIData() {
   // API Success Block
    this.busyGettingData = false

 // API Error Block
this.busyGettingData = false
}

**Comment by sunny7899** [comment]
@angularui06 Thanks working fine in my case.

**Comment by Rakshithkakathkar** [comment]
Wow, this is so cool 
Thank you @angularui06! 😃

**Comment by lzatloukal** [comment]
@angularui06 It`s working. Thank you for the solution.
