### ISSUE TITLE
Is there a way to set the scrollbar at the start of the <div>

### ISSUE THREAD

**Issue by lippomano** [orizens/ngx-infinite-scroll#201]
My page have 2 different views, if I scrolldown many times and after that I change the view I want that the scrollbar goes up at the start of the div tag.
Is there a way to set the scrollbar at the start of the `<div>`?

**Comment by orizens** [comment]
what do you mean by setting the scrollbar?

**Comment by lippomano** [comment]
I'm going to explain better the problem: in short I've to refresh teh entire list of items when the use makes a filter. In this case I want to refresh the view and to show again the first page. I want tell to infinitescroll to reset its internal data. I want the thumb of the scrollbar come back in it's original position at the top.

**Comment by orizens** [comment]
this issue isn't related to infinite-scroll. 
one way to achieve that is setting the [scrollTop of the container to zero](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop).

**Comment by lippomano** [comment]
Ok thanks
