### ISSUE TITLE
AOT build is failing for me

### ISSUE THREAD

**Issue by nolafs** [orizens/ngx-infinite-scroll#204]
Hi,
I am having issues building the production build with the scroller. I am keep getting the following error. 

Supplied parameters do not match any signature of call target

Normal build works fine. Any idea?

Cheers
Olaf

**Comment by orizens** [comment]
please share the entire error produced by ```ng build --aot``

**Comment by bellagamba** [comment]
I am having the same error building:
"Supplied parameters do not match any signature of call target."

<div class="results"
data-infinite-scroll
[infiniteScrollDistance]="scrollDistance"
[infiniteScrollUpDistance]="scrollUpDistance"
[infiniteScrollThrottle]="throttle"
(scrolled)="loadUserListLazy()"
[scrollWindow]="false">

**Comment by orizens** [comment]
@nolafs please try latest 0.8.0.
aot does work - so maybe it's something else. usually, error should output a description.

**Comment by Oipo** [comment]
I also have this issue with 0.8.2. This is the output I have:

```
$ ng build --aot
Date: 2018-01-31T15:57:07.374Z
Hash: 2b9002d1a076c6d5e954
Time: 4733ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 303 bytes [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 323 bytes [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 181 kB [initial] [rendered]

ERROR in : Unexpected module 'InfiniteScrollModule in C:/Users/Oipo/Documents/mcc_mns_new/Source/Backend/MNS/Web/MNS.WebV2/node_modules/ngx-infinite-scroll/ngx-infinite-scroll.d.ts' declared by the module 'AppModule in C:/Users/Oipo/Documents/mcc_mns_new/Source/Backend/MNS/Web/MNS.WebV2/src/app/app.module.ts'. Please add a @Pipe/@Directive/@Component annotation.
```

**Comment by Oipo** [comment]
Sorry for polluting this issue, I had the same thing as described in https://github.com/orizens/ngx-infinite-scroll/issues/214.

**Comment by orizens** [comment]
@Oipo so you were able to solve it?

**Comment by Oipo** [comment]
Yes.

**Comment by orizens** [comment]
@nolafs were you able to resolve this issue following @Oipo suggestion?
