### ISSUE TITLE
Unable to set infiniteScrollDistance to less than 1

### ISSUE THREAD

**Issue by brandonreid** [orizens/ngx-infinite-scroll#205]
I'm trying to set an `infiniteScrollDistance` to `0.5` as the initial content isn't tall enough to create a full view height scroll distance.

I can set decimal values greater than 1 (e.g. `1.5`), but when I go below 1 nothing fires. I've tried `.5`, `0.5`, neither works.

Thanks in advance.

**Comment by orizens** [comment]
can you pleas share an example in plunkr?

**Comment by orizens** [comment]
fixed by 269b5f6dd84125698620ffce8f0f8b4b1a1bafe5
