### ISSUE TITLE
Does not work in IE when created with current Angular CLI

### ISSUE THREAD

**Issue by 2ajoyce** [orizens/ngx-infinite-scroll#211]
## Example
[Demo](https://github.com/2ajoyce/infiniteScrollDemo)
This is a fresh and minimal Angular CLI project that hits an API to retrieve a list.

## Problem
The package does not work in Internet Explorer 11.

## Steps to reproduce
* Visit the demo site in IE11 or clone down the project and host it yourself for testing. 
* Scroll to the bottom of the page.
* **Expectation:** More data should load automatically. 
* **Reality:** Nothing happens. 
* The presence of more data can be confirmed by manually clicking the button.

**Comment by orizens** [comment]
should be fixed with #203

**Comment by orizens** [comment]
now available in version 0.7.0 81616aef925e92162d9f7a34194c825decb5154c
