### ISSUE TITLE
Dragging the scroll container sometimes doesn't trigger scroll event.

### ISSUE THREAD

**Issue by codemasterover9000** [orizens/ngx-infinite-scroll#212]
Situation: When dragging the infinite-scroll container down in our application, the scroll event will sometimes fail to trigger. If the scroll bar ends up at the bottom of the screen the user needs to scroll up a bit to trigger the event. This may lead to confusion as a user may assume they have reached the end of the list while this is not the case. Since the situation does not always occur, a race condition may be the cause.

alwaysCallback is set to true
scrollWindow is set to false

**Comment by orizens** [comment]
hi @codemasterover9000 
please try the latest 0.8.0 - it fixed an issue with this behavior.
if you still experience issues - please reproduce in a plunkr and reopen this issue.
