### ISSUE TITLE
Switch Scroll Direction On Window Resize

### ISSUE THREAD

**Issue by Reece387** [orizens/ngx-infinite-scroll#215]
I have an application that scrolls horizontally and it works fine in the aspect but I am now planning for mobile development and when the viewport is mobile size the application switches to vertical scrolling.

Is there a way to dynamically change [horizontal] and [scrollWindow] to allow switching from horizontal to vertical scroll loading? or maybe another solution I am missing?

**Comment by orizens** [comment]
duplicated https://github.com/orizens/ngx-infinite-scroll/issues/91
