### ISSUE TITLE
UNMET PEER DEPENDENCY @angular/core@4.4.6

### ISSUE THREAD

**Issue by kgcorner** [orizens/ngx-infinite-scroll#219]
I'm not sure whether this is due to angular or something else. But i'm not able to install ngx-infinite-scroll either with angular 4 or 5
in angular 5 i get error 
**UNMET PEER DEPENDENCY @angular/core@5.0.3 
UNMET PEER DEPENDENCY @angular/common@5.0.3**
with angular 4 below is the log
Can you please tell me is there any workaround if not fix?

_npm install ngx-infinite-scroll --save
news-craweler-admin@0.0.0 /work/indicainfomedia/news-crawler-admin
├── UNMET PEER DEPENDENCY @angular/core@4.4.6
└── ngx-infinite-scroll@0.7.2

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @angular/animation@4.0.0-beta.8 requires a peer of @angular/core@4.0.0-beta.8 but none was installed.
npm WARN @schematics/angular@0.0.49 requires a peer of @angular-devkit/schematics@0.0.34 but none was installed._

**Comment by StarFox00007** [comment]
Same error when I tried to install popover ! 
![image](https://user-images.githubusercontent.com/32387837/34149707-448b715e-e4a6-11e7-86f7-e011de0f18c7.png)

I don't see how to fix it... Someone to help us ?

**Comment by orizens** [comment]
@StarFox00007  that's not coming from ngx-infinite-scroll.

**Comment by orizens** [comment]
@kgcorner please consult the plunkr demo https://plnkr.co/edit/DrEDetYnZkFxR7OWWrxS
