### ISSUE TITLE
Scrolled triggers as soon as i scroll just a little

### ISSUE THREAD

**Issue by Prasannavk94** [orizens/ngx-infinite-scroll#224]
I want the event to be triggered only when the scroll reaches the bottom of the window.  

But scrolled event triggers as soon as i scroll just a little.

**Comment by cerebroo** [comment]
@Prasannavk94 - Experiencing same thing but on scroll up, how did you fix it?

**Comment by sahngah** [comment]
Hi, did you ever fix this issue? I'm facing the same problem and none of the solutions here works.

**Comment by orizens** [comment]
hi @sahngah 
please open a new issue and follow guidelines.
