### ISSUE TITLE
Firefox requests entry multiple times

### ISSUE THREAD

**Issue by jsauvain** [orizens/ngx-infinite-scroll#226]
I am developing an application which loads new images with this module. I encountered a problem, that the (onScroll) is being fired multiple times for the same scroll. Even if the Throttle is on 100 the onScroll is being called twice

![image](https://user-images.githubusercontent.com/26246276/34692769-913b57e6-f4c1-11e7-907e-4a2f8e735749.png)

**Comment by orizens** [comment]
hi @jsauvain 
does this happen with the demo as well? 
https://plnkr.co/edit/DrEDetYnZkFxR7OWWrxS?p=preview ?

**Comment by jsauvain** [comment]
It actually does not happen on the demo. I assume that it's been an issue in cause of the async request of the data from a REST Service but I cannot confirm it yet

**Comment by orizens** [comment]
please checkout latest 0.8.2

**Comment by orizens** [comment]
hi @jsauvain does this still happen ? if so - please share a demo reproducing this.

**Comment by jsauvain** [comment]
This bug is fixed :)
