### ISSUE TITLE
Fast scrollUp

### ISSUE THREAD

**Issue by lousley** [orizens/ngx-infinite-scroll#227]
When I scroll up too quickly, it seems like the scroller handler isn't firing so I'm stuck at the top even though there are more records to load.

i use folowing settings:

[scrollWindow]="false"
[infiniteScrollDistance]="2"
[infiniteScrollUpDistance]="2"
[infiniteScrollThrottle]="50"

**Comment by orizens** [comment]
please share a plunkr

**Comment by orizens** [comment]
closed for a lack of activity.

**Comment by hexadeciman** [comment]
seems to be refering to the same issue here : https://github.com/orizens/ngx-infinite-scroll/issues/250
Example: https://stackblitz.com/edit/angular-9nx2jt?file=app%2Fapp.component.html
