### ISSUE TITLE
Scroll event only fires once when the underlying array has items removed from it

### ISSUE THREAD

**Issue by SamFarrington** [orizens/ngx-infinite-scroll#229]
I am in the process of migrating from angular2-infinite-scroll to ngx-infinite-scroll and some functionality that worked in angular2-infinite-scroll no longer works in ngx-infinite-scroll.

My use case is where the number of items in the array remains constant and when a user scrolls down, items are added to the end of the array and taken from the start of the array (and vice versa when scrolling up)

When doing this, the scroll event only fires once, seemingly breaking after items are removed from the array.

Here is a plunker demonstrating this behaviour (navigate to app.ts in the editor to see).

https://plnkr.co/edit/SIkYlwwQjzGv3n8eYh3N?p=preview

This worked without issue in angular2-infinite-scroll - I am not sure whether this is a bug or if there is a another way to implement the desired functionality?

**Comment by orizens** [comment]
the behavior you'r describing is considered a bug.  
From another perspective, you are describing a feature of a carousel - which is not meant to be supported in the functionality of an infinite-scroll component.
if there are more requests for this behavior, this can be considered to be a feature request (you're also welcome to make a pr that supports that). 
thanks.

**Comment by SamFarrington** [comment]
Thank you for getting back to me on this - I appreciate working as a sole contributor can be difficult!

Out of curiosity - this "carousel" functionality worked in angular2-infinite-scroll - was it a conscious decision to remove this functionality with the move to  ngx?

Or was this "carousel" functionality only ever a happy accident that happened to meet my use case?

**Comment by orizens** [comment]
hi.
the carousel functionality was actually not intentional - so yes - it was an accident that meet your case :)
sorry about that.

**Comment by SamFarrington** [comment]
No worries, thanks for getting back to me - good luck with the library going forward!
