### ISSUE TITLE
[BUG] Scroll event when I change the sort of the array

### ISSUE THREAD

**Issue by kevincaradant** [orizens/ngx-infinite-scroll#230]
Hi

I didn't have enough time to do a plunker for the moment. I will edit this issue, more later, if you don't understand the problem.

If I use the infinitescroll on an array <md-table> and then I scroll down until the end, you added in (0.8.2) a feature to stop the event scroll, isn't it ? 

If I change after that the sort order ( DESC , ASC ), it's too late, your infiniteScroll doesn't work anymore. No event scroll catched :/

Tested with Windows 7 and Chrome browser.

**Comment by orizens** [comment]
hi.
please add a plunkr or https://stackblitz.com/

**Comment by kevincaradant** [comment]
OK no problem, can you provide me a beginning of example from plunker or stackblitz with angular + your library loaded and currently working ? 

That can help me to win some time ;)

**Comment by kevincaradant** [comment]
@orizens, Did you have time to create a stackblitz or plunker demo ? :)
