### ISSUE TITLE
Not working properly when state changes with scrollWindow true

### ISSUE THREAD

**Issue by NikhilRadadiya** [orizens/ngx-infinite-scroll#232]
I'm trying to use this with `ng2-table`. when page loads for first time it works properly but when I go to other page and come back to that page it loads more loads then passed length (for Ex: 10). I'm using `scrollWindow=true` option because its not looking good with fixed height table. Only problem is when state changes

Here is code : 
```
<div class="search-results"
        infiniteScroll
       [infiniteScrollDistance]="1"
       [infiniteScrollThrottle]="100"
        (scrolled)="lazyLoadUsers()"
        [scrollWindow]="true"
  >
```
```
.search-results {
      height: 100% ;
      clear: both;
}
```
It should load only 10 records
Please help me out.
Thanks

**Comment by orizens** [comment]
hi.
please reproduce in plunkr or https://stackblitz.com/

**Comment by orizens** [comment]
lack of more info.
