### ISSUE TITLE
Demos are not working

### ISSUE THREAD

**Issue by SebastianSchenk** [orizens/ngx-infinite-scroll#233]
The demo plunkers are both not working. Multiple errors are thrown.

[https://plnkr.co/edit/DrEDetYnZkFxR7OWWrxS?p=preview](https://plnkr.co/edit/DrEDetYnZkFxR7OWWrxS?p=preview)
[https://plnkr.co/edit/QnQOwE9SEapwJCCFII3L?p=preview](https://plnkr.co/edit/QnQOwE9SEapwJCCFII3L?p=preview)

**Comment by orizens** [comment]
@SebastianSchenk thanks.
fixed.
