### ISSUE TITLE
Reset scroll on the page when search results changes

### ISSUE THREAD

**Issue by prashantnorbrik** [orizens/ngx-infinite-scroll#236]
Awesome add-on!

I am developing an app in angular 5.x which has a search page to return data based on search parameters. 
The infinite scroll is working in the first instance but when I search again and the result set is different it stops working. 

It looks like there is a flag which tell infinite scroll that there is no more data to load. 

Please help!

**Comment by orizens** [comment]
sounds like your data is not changed. infinite-scroll checks the height has changed and then upon arriving to the distance point, triggers an event.

**Comment by prashantnorbrik** [comment]
Thank you for the quick reply.  I can see that the data has changed and so has the height.

The data is changing when I search again using a different query but the scroll is not triggering any more on the second search.



Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by prashantnorbrik** [comment]
Thank you @orizens  again for the component. 

Looks like I had very few items in my view before and the issue is not there with some real data in my system. 

I appreciate your prompt response and closing this now. 
Will raise issue if I get it again.

**Comment by rupesh45** [comment]
I'm having the same issue! When a first-time event is called it works fine! but when I do the query and the array changes It won't get triggered!
