### ISSUE TITLE
question about performance

### ISSUE THREAD

**Issue by AyaSypron** [orizens/ngx-infinite-scroll#237]
Hi there!
Firstly, I'd like thank you for sharing such a great package. Secondly, I have a question about how it works and its performance. You've mentioned that:

>  the directive listens to the window scroll event and invoked the callback 

I wanna make sure that the directive listens **only** to the events of its own, In other words it stops listening if I navigated away to another page?

Thanks in advance.

**Comment by orizens** [comment]
hi.
as long as the component which consume ngx-infinite-scroll is destroyed, ngx-infinite-scroll is destroyed as well.

**Comment by AyaSypron** [comment]
I get it now, Thank you!
