### ISSUE TITLE
Can't bind to 'scrollWindow' since it isn't a known property of 'div'.

### ISSUE THREAD

**Issue by iktuz** [orizens/ngx-infinite-scroll#238]
I am using **Angular 4.3.6** with **ngx-infinite-scroll 0.8.2** as described in the documentation and it is working fine when I run the application through **ng serve**. However, when I run my **ng test** I get these errors:

`
Can't bind to 'scrollWindow' since it isn't a known property of 'div'. ("
            <div class="messages"
                 infiniteScroll
                 [ERROR ->][scrollWindow]="false"
                 [infiniteScrollDistance]="2"
                 [infiniteScrollThrottle]="250" />
        "): ng:///DynamicTestModule/TipsComponent.html@9:9
        Can't bind to 'infiniteScrollDistance' since it isn't a known property of 'div'. ("
                 infiniteScroll
                 [scrollWindow]="false"
                 [ERROR ->][infiniteScrollDistance]="2"
                 [infiniteScrollThrottle]="250"
                 (scrolled)="onScrollDow"): ng:///DynamicTestModule/TipsComponent.html@10:9
        Can't bind to 'infiniteScrollThrottle' since it isn't a known property of 'div'. ("
                 [scrollWindow]="false"
                 [infiniteScrollDistance]="2"
                 [ERROR ->][infiniteScrollThrottle]="250"
                 (scrolled)="onScrollDown()">
        "): ng:///DynamicTestModule/TipsComponent.html@11:9
        Error: Template parse errors:
`
I have seen some posts regarding this issue, but have no success solving this:

[https://github.com/orizens/ngx-infinite-scroll/issues/179](url)
[https://github.com/orizens/ngx-infinite-scroll/issues/222](url)

What I have tried:

1) If I remove the square brackets, the **ng test** runs successfully, but the scroll effect does not work any more. 
2) Adding an export for InfiniteScrollModule in my@NgModule but no success at all.

I do have the import module in my @NgModule as well.

Any clues?

**Comment by iktuz** [comment]
Found the error. My .spec.ts class had no import for InfiniteScrollModule. This does the trick:

`TestBed.configureTestingModule({
      imports: [
        HttpModule,
        HttpClientModule,
        AppRoutingModule,
        FormsModule,
        ReactiveFormsModule,
        InfiniteScrollModule
      ],`

Best Regards.

**Comment by agiratech-vigneshm** [comment]
this error happens to me when serving using ng serve

**Comment by iktuz** [comment]
@agiratech-vigneshm, make sure you have all the component declarations in its right places. In my case, my test classes were missing it. Review your core, modules etc.

**Comment by agiratech-vigneshm** [comment]
@iktuz  Bullseye, It was a problem with my component structure. I created a shared module for lazy loading and added the directive to app module instead of the shared module so angular doesn't know the directive properties.
