### ISSUE TITLE
Throttle doesn't appear to be doing anything to prevent scrolled event from being fired too often

### ISSUE THREAD

**Issue by chrillewoodz** [orizens/ngx-infinite-scroll#241]
I've been playing around with the throttle in one of my apps because when I scroll I fire http requests to my API which fetches more items. 

However they fire way too often so I end up with 10-15 pending requests. Having a throttle of `150` or `500` doesn't do anything. The `scrolled` event still fires every time the scroll distance requirement is met. 

Shouldn't throttle work as `debounceTime` does in RxJS? I.e. it should not allow `scrolled` to be fired more than every `x` milliseconds. 

This is driving me nuts so a response would be great.

**Comment by orizens** [comment]
hi @chrillewoodz 
can you setup an example which demonstrate the issue you're facing?

**Comment by chrillewoodz** [comment]
I will try to do it sure.

**Comment by marvin-SL** [comment]
Same for me, even when I first installed it and did the "Usage" part.
It says "scrolled!! multiple times (from 2-3 times to 30 times...). Same result from my rest API.
