### ISSUE TITLE
Problem in smooth scroll

### ISSUE THREAD

**Issue by Amitmundra** [orizens/ngx-infinite-scroll#243]
Hi,
I am loading data on scrolling. what are we doing:
we are showing some data at initially.
On scroll we are fetching some data, which is in local cache(To load data without showing loading indicator as its fast).
After loading data from cache we are setting scroll position to visible(maintain scroll position) content.
But when scroll fast then it doesn't load data properly and scrolled reached at top.

We are using Angular4.
Any idea to resolve scroll issue and maintain the position of scroll?

**Comment by makssie** [comment]
I have some problem.

**Comment by orizens** [comment]
@Amitmundra need to see an example of the issue.

**Comment by Amitmundra** [comment]
Its difficult to show you as an example:
let me explain steps once more:
1) Initially load 25 messages.
2) Keep next 25 messages in local cace, we may say, keep in type script.
3) When user scroll up then before reach to top(can say  before 10% of top) then showing next 25 records from cache and then set scroll potion
4) Then calling server api to get next 25 record at same time and keeping in local cache.
5) continuously doing same thing from setp 2.
6) At some point scroll reached at top and position setting does't work properly and data stop loading.
7) After that we need to down the scroll little bit then take at top then again scrollload next rows.

May any one help to record issue?

**Comment by orizens** [comment]
@Amitmundra i think you're describing a virtual scroll behavior - which is not supported with this plugin. 
rather, you should add items to the array that is rendered inside the scrollable container.
