### ISSUE TITLE
How could I disable infinite scroll after max length?

### ISSUE THREAD

**Issue by rolandoesc** [orizens/ngx-infinite-scroll#246]
Is there a way I can disable Infinite Scroll if I reached the length of my array?

I'm using an array that has around 800 elements and I filter them so I can find what I look for, however if it reaches the max length, it still creates elements, is there a way it can be disabled?

Thank you

**Comment by neilhem** [comment]
Use `infiniteScrollDisabled` directive, example:
```js
<div infiniteScroll [infiniteScrollDisabled]="maxLengthReached"></div>
```

**Comment by orizens** [comment]
closing as it seems issue has been resolved.
