### ISSUE TITLE
Cannot read property 'nativeElement' of null

### ISSUE THREAD

**Issue by olivaresdeveloper** [orizens/ngx-infinite-scroll#247]
when I try to access the scrooll with` [infiniteScrollContainer] = "'.class'" [scrollWindow] = "false"` I get the error Can not read property 'nativeElement' of null,
 if I delete ` [infiniteScrollContainer] = "'. class'" [scrollWindow] = "false"` the error disappears but the infinite scroll does not work.

**Comment by orizens** [comment]
please follow the issue template (was is deleted??) and share an example.
