### ISSUE TITLE
Observable.fromEvent is not a function in Scroll Register Directive

### ISSUE THREAD

**Issue by jcroll** [orizens/ngx-infinite-scroll#248]
Hey @orizens, 

After upgrading my project to Angular 5 and RxJS 5.5 there seems to be a compilation error with the RxJs import `fromEvent` in the [scroll register directive](https://github.com/orizens/ngx-infinite-scroll/blob/master/src/services/scroll-register.ts#L66).

Please see below some webpack output:

![screen shot 2018-03-12 at 11 41 58 am](https://user-images.githubusercontent.com/1441013/37293688-6e4bced2-25ea-11e8-81c9-5f8790974b1f.png)

I'm going to try and open a quick pr but I admit I'm confused about some of the rxjs imports in this file. I've never had to maintain a library that works with different rxjs and angular versions all at once and I'm quite sympathetic that this is probably difficult and frustrating to maintain.

But looking at the imports:

![screen shot 2018-03-12 at 11 47 56 am](https://user-images.githubusercontent.com/1441013/37294019-47f41b30-25eb-11e8-9c57-d83b836a41c6.png)

Line 1-7 are what I'd say are *classical* rxjs import where line 11-12 I'd say are RxJs 5.5 imports. Is it possible to mix the two? 

Additionally the Observable being created on [line 66](https://github.com/orizens/ngx-infinite-scroll/blob/master/src/services/scroll-register.ts#L66):
```typescript
let obs = Observable.fromEvent(options.container, 'scroll');
```
 is being create from a classic creation operator where an observable being created on [line 46](https://github.com/orizens/ngx-infinite-scroll/blob/master/src/services/scroll-register.ts#L46):
```typescript
.mergeMap((ev: any) => of(calculatePoints(element, resolver)))
```
is being created from one of RxJs 5.5's new functional operators.

An additional thing I am confused about is that the `map` operator has been imported in this file in two different ways (lines 5 and 11).

I'm going to open a pr with the fromEvent imported in the new way, if this is not the correct approach feel free to close it.

**Comment by hxltinh** [comment]
Now i'm facing this error on my Mac mini (High-Sierra 10.13.3, node version 8.9.4), hope it will be fixed soon
