### ISSUE TITLE
how can i implement the same concept on the table 

### ISSUE THREAD

**Issue by syedirfan7** [orizens/ngx-infinite-scroll#257]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior
want to implement infinite scroll on table
### Your Environment

- [ ] Version used: Angular 5 

- [ ] (Optional) Operating System and version (desktop or mobile): web

**Comment by orizens** [comment]
please add an example of such table

**Comment by szafirov** [comment]
`    <table class="table table-fixed-header table-bordered">
        <thead>
        <tr>
            <th><strong>ID</strong></th>
            <th><strong>Name</strong></th>
        </tr>
        </thead>
        <tbody [style.height.px]="height" infinite-scroll [scrollWindow]="false">
        <tr *ngFor="let feature of scrollingFeatures; let i = index;"
            infinite-scroll
            [fromRoot]="true"
            [infiniteScrollDistance]="2"
            [infiniteScrollThrottle]="50"
            [infiniteScrollContainer]="'tbody'"
            (scrolled)="onScrollDown()"
            (scrolledUp)="onScrollUp()">
            <td>{{ feature.featureId }}</td>
            <td>{{ feature.featureName }}</td>
        </tr>
        </tbody>
    </table>`

**Comment by syedirfan7** [comment]
@orizens  [this is the table i am looking for ](https://github.com/ggmod/angular-5-data-table)

in the above there is a table by name demo3 over which i am targeting 
initially i applied the infinite scroll  on <tbody> but its giving the alignment issues
is there a better way to do so ?

**Comment by syedirfan7** [comment]
@szafirov  how do i initialize scrollFeatures(). or how does it get called for the first time ?

**Comment by szafirov** [comment]
Sorry, didn't see your question until today. I guess it's too late, but just in case, I used Bootstrap CSS and updated the init code above.
