### ISSUE TITLE
opencollective: command not found on Jenkis or other CI

### ISSUE THREAD

**Issue by bastienmoulia** [orizens/ngx-infinite-scroll#260]
## Expected Behavior
Build project with ngx-infinite-scroll

## Actual Behavior
The build fail when ngx-infinite-scroll launch the postinstall command `opencollective postinstall`.
There is the message :  
```
sh: opencollective: command not found

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ngx-infinite-scroll@0.8.3 postinstall: `opencollective postinstall`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ngx-infinite-scroll@0.8.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

## Possible Solution
Replace opencollective by [opencollective-postinstall](https://github.com/opencollective/opencollective-postinstall) because it not need a cli.

### Steps To Reproduce / Demo (if applicable)
Install ngx-infinite-scroll from another project with an empty node_modules with Jenkins

### Your Environment

- [x] Version used: 0.8.3

**Comment by orizens** [comment]
@bastienmoulia thanks for this. 
just to note: this happens if a developer forks this repo and tries to run it (and not using the directive).

**Comment by orizens** [comment]
@bastienmoulia i tried using `opencollective-postinstall` - it doesn't work well - and requires the project that is using ngx-infinite-scroll to setup their project as an opencollective project.
