### ISSUE TITLE
ScrollUp does not fire or fires repeatedly

### ISSUE THREAD

**Issue by tuckerjt07** [orizens/ngx-infinite-scroll#267]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior
Scroll up should fire when the top percentage of the container is reached and should only fire once.

## Actual Behavior
Scroll up is only firing if the percentage is set to 60% or above. Additionally when it does fire it triggers a cascading event that ends up firing until the API quits returning data.

### Steps To Reproduce / Demo (if applicable)
In progress

### Context
Working to load previously read messages in response to the user scrolling up a list built using a ul and *ngFor.

### Your Environment
Google Chrome Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by speggos** [comment]
Also having this issue. Has anybody found a solution?

**Comment by tuckerjt07** [comment]
I also wonder if it could have something to do with throttling not working.

**Comment by orizens** [comment]
for scroll up to work, the container needs to have the scroll set to be at the bottom OR after the "distanceUp" point.

**Comment by JBrownie77** [comment]
Could you expand upon your answer a little more? I'm not quite clear what I would need to change

I'm using this for my container:

/* Scroll-contents, but start at bottom of container */
.scroll-contents-bottom {
    flex-grow: 1;
    overflow: auto;
    display: flex;
    flex-direction: column-reverse;
}

and tried using the default infiniteScrollUpDistance of 1.5, but it won't trigger.
I can get it to trigger if I change infiniteScrollUpDistance to 8, but that isn't ideal to have it requesting more items after only 20%.

**Comment by JBrownie77** [comment]
ping. It would be great to get this working

**Comment by vishal-pk** [comment]
The fix for this issue is the infiniteScrollUpDistance should be a negative number when the column is reverse. I used -9 as the infiniteScrollUpDistance value and it worked for me
