### ISSUE TITLE
Doesn't work at all with Angular Material Dialog

### ISSUE THREAD

**Issue by ivmarkp** [orizens/ngx-infinite-scroll#268]
## Expected Behavior
Should work with Angular material dialog.

## Actual Behavior
Scroll events like "scrolled" don't bind to material dialog elements like `mat-diag-content`.

**Comment by orizens** [comment]
please complete issue template and add a demo.

**Comment by orizens** [comment]
please supply an example using stackblitz

**Comment by orizens** [comment]
https://github.com/orizens/ngx-infinite-scroll/issues/98#issuecomment-394077907

**Comment by Brhav** [comment]
Solved by using [infiniteScrollContainer]="'.mat-dialog-content'"
