### ISSUE TITLE
scrolledUp not firing

### ISSUE THREAD

**Issue by JBrownie77** [orizens/ngx-infinite-scroll#269]
First, thanks for creating this. It's super handy!

Not sure if this is a bug (although it seems like it). I am using flex to reverse the scroll to be from the bottom (like a text conversation).

/* Scroll-contents, but start at bottom of container */
.scroll-contents-bottom {
    flex-grow: 1;
    overflow: auto;
    display: flex;
    flex-direction: column-reverse;
}

I want to trigger more items to load on (scrolledUp), but it never fires. I thought it might be related to reversing the scroll direction, so to test it I added (scrolledUp) to another regular list that is already working with (scrolled) and it still didn't fire.

Is there a trick to getting (scrolledUp) to work?

**Comment by JBrownie77** [comment]
I should also note that if I add alwaysCallback then it fires, but I think that's a hack rather than the actual solution since it fires almost immediately rather than when the scroll point is reached

**Comment by orizens** [comment]
closing because of #267
