### ISSUE TITLE
Angular 6, rxjs 6 support

### ISSUE THREAD

**Issue by iozozturk** [orizens/ngx-infinite-scroll#271]
Angular 6 is released, I think this will be a small fix about rxjs6. 

 > ERROR in ./node_modules/ngx-infinite-scroll/modules/ngx-infinite-scroll.es5.js
Module not found: Error: Can't resolve 'rxjs/observable/fromEvent' in '/Users/ismet.ozozturk/Desktop/mesele/mesele-frontend/node_modules/ngx-infinite-scroll/modules'
ERROR in ./node_modules/ngx-infinite-scroll/modules/ngx-infinite-scroll.es5.js
Module not found: Error: Can't resolve 'rxjs/observable/of' in '/Users/ismet.ozozturk/Desktop/mesele/mesele-frontend/node_modules/ngx-infinite-scroll/modules'

### Environment
- [ ] Version used: 0.8.4

**Comment by kuncevic** [comment]
@orizens any eta on that?

**Comment by manojcena** [comment]
same error here.

./node_modules/ngx-infinite-scroll/modules/ngx-infinite-scroll.es5.js
Module not found: Error: Can't resolve 'rxjs/observable/fromEvent' in 'C:\Users\scketcher\Desktop\NoQAdmin\node_modules\ngx-infinite-scroll\modules'

**Comment by phl3x0r** [comment]
for quick fix while PR is resolved, just `npm i rxjs-compat`

**Comment by tailot** [comment]
@orizens any news ? :face_with_head_bandage:

**Comment by orizens** [comment]
i'll try to make an effort to make a release in the next following week.

**Comment by orizens** [comment]
v0.9.0 released https://github.com/orizens/ngx-infinite-scroll/commit/db675216751cd6eed767dc74f46c55bfad76c8ab
