### ISSUE TITLE
infiniteScrollDistance calculate wrong

### ISSUE THREAD

**Issue by live9080** [orizens/ngx-infinite-scroll#273]
When `infiniteScrollContainer` is empty,  the `infiniteScrollDistance`  calculate wrong.

## Expected Behavior
In the demo link "https://plnkr.co/edit/DrEDetYnZkFxR7OWWrxS?p=preview",

The Expected Behavior is  "should add the next 20 items when scroll to 90% position."

## Actual Behavior
The Actual Behavior is "add the next 20 items when scroll to almost 70% position"

## Possible Solution
It seems that the  `scrolledUntilNow`  add `height` twice.

shouldFireScrollEvent in ngx-infinite-scroll/src/services/scroll-resolver.ts 
`const scrolledUntilNow = container.height + container.scrolled;`

calculatePointsForWindow in ngx-infinite-scroll/src/services/position-resolver.ts
`// scrolled until now / current y point
  const scrolled =
    height +
    getElementPageYOffset(
      getDocumentElement(isWindow, container),
      axis,
      isWindow
    );`

### Your Environment

- [x] Version used:  0.8.4
- [x] Browser Name and version: Chrome
- [x] (Optional) Operating System and version (desktop or mobile): Win10 desktop

**Comment by Ballrock** [comment]
Hi,

I have same problem now with scrollDown.
Did #282 correct only scrollUp ?

In my case : 
- infiniteScrollContainer - empty
- scrolledUntilNow add 2 time height (_calculatePointForWindow_ AND _shouldFireScrollEvent_)

It result to event fire nearly immediatly after first scroll (_remaining_ is negative)

**Comment by julamb** [comment]
+1, I seem to have the same problem with scrollDown. Setting `infiniteScrollDistance` to 0 but the onScroll event is triggered before I reach the bottom of the container. Removing the height addition from `shouldFireScrollEvent ` fixed it.

**Comment by play2web** [comment]
How did you fixed it?

**Comment by julamb** [comment]
Replaced `const scrolledUntilNow = container.height + container.scrolled;` by `const scrolledUntilNow = container.scrolled;` in the `shouldFireScrollEvent` function here:
https://github.com/orizens/ngx-infinite-scroll/blob/master/src/services/scroll-resolver.ts

Seems to work for me so far but not sure it's the perfect fix.

**Comment by bertdewolf** [comment]
Can this fix be ported to version that supports angular 4? We are using version 0.8.4 and we need this fix.
