### ISSUE TITLE
not working with rxjs 6

### ISSUE THREAD

**Issue by maapteh** [orizens/ngx-infinite-scroll#276]
## Expected Behavior
Since Angular 6 is out for some weeks now i expected an updated module :)

## Actual Behavior
`ERROR in ./node_modules/ngx-infinite-scroll/modules/ngx-infinite-scroll.es5.js
Module not found: Error: Can't resolve 'rxjs/observable/fromEvent' in XXX/node_modules/ngx-infinite-scroll/modules'
ERROR in ./node_modules/ngx-infinite-scroll/modules/ngx-infinite-scroll.es5.js
Module not found: Error: Can't resolve 'rxjs/observable/of' in 'XXX/node_modules/ngx-infinite-scroll/modules'`

## Possible Solution
Run rxjs migration plugin and done()

### Steps To Reproduce / Demo (if applicable)
Run it with Angular6 withouth rxjs compat dependency

### Context
I have to get rid of this plugin if it doesn't get updated.

### Your Environment
Rxjs 6.0.2 with Angular 6

**Comment by Charius** [comment]
see https://github.com/orizens/ngx-infinite-scroll/issues/271

I think release will be soon

**Comment by maapteh** [comment]
Ok thanks, since build size with compat is unacceptable this is the only module we are waiting for :)

**Comment by orizens** [comment]
v0.9.0 https://github.com/orizens/ngx-infinite-scroll/commit/db675216751cd6eed767dc74f46c55bfad76c8ab

**Comment by maapteh** [comment]
Maybe an idea to have your versioning in major the same as in Angular and its modules so its clear this version works from 6 and above?
