### ISSUE TITLE
Try to using ngx-scroll-to bt It's comes error from rxjs/Observable

### ISSUE THREAD

**Issue by VIDYUT4** [orizens/ngx-infinite-scroll#278]
./node_modules/@nicky-lenaers/ngx-scroll-to/@nicky-lenaers/ngx-scroll-to.es5.js
Module not found: Error: Can't resolve 'rxjs/Observable' in 'E:\Angular4 project\AngularNewApp\node_modules\@nicky-lenaers\ngx-scroll-to\@nicky-lenaers'

Currently I'm using angular 6

**Comment by orizens** [comment]
seems this error comes from ngx-scroll-to

**Comment by orizens** [comment]
not relevant to infs
