### ISSUE TITLE
fromRoot/infiniteScrollContainer Implementation issue

### ISSUE THREAD

**Issue by TCNexmo** [orizens/ngx-infinite-scroll#286]
My project is rather complex, I have several elements before reaching the element where the vertical and horizontal scrolls are. To keep it simple I have bellow an example of the issue at hand.
I am almost 100% sure it is not a bad implementation on my part, but a problem related with the ngx-infinite-scroll fromRoot attribute and/or infiniteScrollContainer.

## Expected Behavior
Setting the attribute fromRoot to true (default=false), and assigning the name of the class to the infiniteScrollContainer attribute. This would then tell the ngx-infinite-scroll module what container to trigger the horizontal or vertical events in.

## Actual Behavior
By implementing it this way 

> https://stackblitz.com/edit/ngx-infinite-scroll-tc-example?file=src/app/app.component.html

  You can see that there is no triggering of any events vertical or horizontal, with or without the horizontal attribute.
This implementation would be ideal for my case (if the events were to trigger), because if you check the resolver variable in the module (by downloading the source code and importing directly from the local project, file scroll-regiter.ts), you can see which container it is aiming at (default being Window when fromRoot is false).

This is an example of the implemetation without the fromRoot attribute and infiniteScrollContainer attribute

>  https://stackblitz.com/edit/ngx-infinite-scroll-tc-example-2?file=src%2Fapp%2Fapp.component.html 

this one works as you can see, but it is not ideal for me. In the project I am working I need a inner element that is not Window. If I were to use this example in my project, it will not detect any horizontal or vertical events.

Summing it up, the problem at the moment seems to be that I cannot get horizontal or vertical events when trying to use infiniteScrollContainer to reference the container I want the scroll events to be triggered in.

### Context
The project I'm developing has a container where a table is displayed, we are talking about a 200 x 100 table. Since it is a rather large table, the way I though of optimizing was to load the information by parts, so the user would not have to wait for all of it to load up. Ideally I would like to implement ngx-infinite-scroll to detect vertical and horizontal events at the same time, but from what I understand, at this moment, it is not possible, so implementing for one of the events (vertical or horizontal scrolling)  would be a great step!

### Environment
Angular CLI: 6.1.0-rc.0
Node: 8.9.4
OS: win32 x64
Angular: 6.0.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Browser: Google Chrome Version 67.0.3396.87 (Official Build) (64-bit)

OS: Windows 7 professional

**Comment by bhavnaberi** [comment]
I am also facing the same issue and have replicated the behavior at https://stackblitz.com/edit/ngx-infinite-scroll-ngdxwc
This is completely blocking us from using this plugin

**Comment by orizens** [comment]
@bhavnaberi 
in the example you posted, the "abc" container is empty - thus - not triggering any scroll events - because there is nothing to scroll.
also - the "abc" container needs to have a height, something like:
```css
.abc {
  background-color: tomato;
  position: absolute;
  height: 300px;
  width: 300px;
  border: 1px solid red;
  overflow: auto;
}
```
