### ISSUE TITLE
Using unescaped '#' characters in a data URI body is deprecated and will be removed in M68, around July 2018.

### ISSUE THREAD

**Issue by MikhailOkhrimenko** [orizens/ngx-infinite-scroll#289]
I see this warning: "[Deprecation] Using unescaped '#' characters in a data URI body is deprecated and will be removed in M68, around July 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details." in the console. I've not seen any problems with it. What might be happening in the future? What can it affect?

### Your Environment

- [ ] Version used: 0.8.4
- [ ] Browser Name and version: WebView 1.1.16
- [ ] (Optional) Operating System and version (desktop or mobile): mobile (Ionic 3.20.0)

**Comment by orizens** [comment]
hi.
please share an example

**Comment by MikhailOkhrimenko** [comment]
I have got a strange behavior. 
Now I'm seeing the following warning: "[Deprecation] Using unescaped '#' characters in a data URI body is deprecated and will be removed in M71, around December 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details." As you can see this warning small different from warning which has been provided by me above. 
The version of ngx-infinity-scroll the same 0.8.4.

**Comment by MikhailOkhrimenko** [comment]
Sorry, this issue is not related with ngx-infinity-scroll at all.
I found the problem. Problem is my fault, I need use '%23' instead character '#' in the SVG content in the CSS property `bacground-image: url("data:image/svg+xml;utf8,<svg>...</svg>)` in the `fill` attribute (`fill='%238ED838'` instead `fill='#8ED838'`) (link: https://github.com/stylus/stylus/issues/2379)
Thanks.
