### ISSUE TITLE
infiniteScrollUpDistance strange behavior

### ISSUE THREAD

**Issue by yume117** [orizens/ngx-infinite-scroll#290]
## Expected Behavior
Call event method when user is scrolling to the top of the list, same as the bottom one

## Actual Behavior
Event is called inconsistently even while trying diferent infiniteScrollUpDistance values

### Steps To Reproduce / Demo (if applicable)
Use 6.0.0 version on a simple list with those params : 
```
        infiniteScroll
        [infiniteScrollDistance]="2"
        [infiniteScrollUpDistance]="1.5"
        [infiniteScrollThrottle]="300"
        (scrolled)="onScrollEvent('bot', $event)"
        (scrolledUp)="onScrollEvent('top', $event)"
        [scrollWindow]="false"
```

### Context
An Angular 6 project with angular cli and in typescript target es5

### Your Environment

- [ ] Version used: 6.0.0
- [ ] Browser Name and version: Chrome

**Comment by orizens** [comment]
please attach a stackblitz demo
