### ISSUE TITLE
scrolledUp don't work!!!

### ISSUE THREAD

**Issue by logicalsisufaj** [orizens/ngx-infinite-scroll#292]
Please can anyone help me with scrolledUp. 
`<div style="height: 99.9%; overflow: auto; flex:none;"
     infiniteScroll
     [infiniteScrollDistance]="2"
     [infiniteScrollUpDistance]="1.5"
     [infiniteScrollThrottle]="0"
     [scrollWindow]="false"
     (scrolled)="onScroll()"
     (scrolledUp)="onUp($event)"

onUp() {
    console.log('scrolled up!!');
}`
I don't now is a bug or not but for me didn't work @orizens

**Comment by orizens** [comment]
duplicate
