### ISSUE TITLE
Problem when scrolling for second time

### ISSUE THREAD

**Issue by logicalsisufaj** [orizens/ngx-infinite-scroll#294]
Hi ,

I am using ngx- infinite-scroll in a project , and I am having some problems . It works when I scroll down , or/and scroll up , for the first time . But when I scroll down or up , again , for a second time , the event does not get triggered anymore .

Can you kindly help me to solve this problem ?

Thank you

**Comment by orizens** [comment]
please repost using the issue template

**Comment by Josh-TX** [comment]
I found a temporary solution that worked for my situation:
1. Get a reference to the viewchild:
` @ViewChild(InfiniteScrollDirective) infiniteScroll: InfiniteScrollDirective;`
2. Sometime before the 2nd scroll-to-bottom, call this:
`this.infiniteScroll.ngOnDestroy();`
`this.infiniteScroll.setup();`

**Comment by AmitJain628** [comment]
Thanks @Josh-TX  for the solution, I am just elaborating more here for Angular 6 and Typescript users

1. Import directive in the file
import { InfiniteScrollDirective } from 'ngx-infinite-scroll';
2. Get a reference to it
@ViewChild(InfiniteScrollDirective)
  set appScroll(directive: InfiniteScrollDirective) {
    this.infiniteScroll = directive;
  }

Then on onScroll function call two methods
 

1. this.infiniteScroll.ngOnDestroy();
2. this.infiniteScroll.setup();

**Comment by McSam94** [comment]
@AmitJain628 after i apply the solution, the event will trigger when i scrolled up. That's weird.

**Comment by satish-mukku** [comment]
@McSam94 I am also facing the same issue, even it is triggering for scrolling up, which is not weird

**Comment by orizens** [comment]
use alwaysCallback=true

**Comment by kamal0912** [comment]
> @AmitJain628 after i apply the solution, the event will trigger when i scrolled up. That's weird.

Hi @McSam94 , I am facing the same issue. Event is getting triggered even when I am scrolling up. have you got any work-around for it ?
