### ISSUE TITLE
Focus doesn't change to div on page down button 

### ISSUE THREAD

**Issue by Automagication** [orizens/ngx-infinite-scroll#295]
I have a search bar, below that i load all items and scroll through window scroll bar.
It works perfect with dragging the scroll bar.

But, after i search and scroll through '**PAGE-DOWN**' button the focus always goes back to the top towards search bar before coming down to result.

Should i change the focus on to the div, because it is a part of the web page and not the only content.

please assist.

Attached is the example of my screen.
![search example](https://user-images.githubusercontent.com/8576187/43697262-9276b346-9960-11e8-8e30-e23ca03d96bc.png)

**Comment by orizens** [comment]
please post an example with stackblitz
