### ISSUE TITLE
Is the dependency on opencollective required? It adds rx v4 to our bundles

### ISSUE THREAD

**Issue by roldengarm** [orizens/ngx-infinite-scroll#296]
## Expected Behavior
the dependency on opencollective is removed.

## Actual Behavior
A dependency on opencollective is present. This depends on inquery, which depends on rx (v4). So, this adds another ~400kb to our bundle.

```
$ yarn why rx
yarn why v1.7.0
[1/4] Why do we have the module "rx"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "rx@4.1.0"
info Reasons this module exists
   - "ngx-infinite-scroll#opencollective#inquirer" depends on it
   - Hoisted from "ngx-infinite-scroll#opencollective#inquirer#rx"
Done in 2.09s
```

**Comment by orizens** [comment]
@roldengarm is used for dev mode only.

**Comment by roldengarm** [comment]
@orizens thank you for your reply. But it's in `dependencies` not in `devDependencies`, so that means it should be moved?
Happy to submit a PR if required.

**Comment by orizens** [comment]
@roldengarm not sure about that - it was added by @opencollective - so i'm not sure opencollective will continue to work when in devDependencies. 
please try and submit a pr if open collective still works (meaning - when ``npm i ngx-infinite-scroll`` - open collective will show up in terminal)

**Comment by giane88** [comment]
When the pull request will be merged in the new version.
Exist a workaround to exlude it, my CI server have some problem that should be solved by the pull request associeted to this issue

**Comment by orizens** [comment]
v7.1.0
