### ISSUE TITLE
[scrollWindow]="false" with CSS height: 100% not working

### ISSUE THREAD

**Issue by alexandremoore** [orizens/ngx-infinite-scroll#297]
If we set [scrollWindow]="false" with a CSS height of 100%, infinite-scroll does not trigger.

If we set an explicit CSS height value in px (or em, rem, etc.) with overflow: auto, then it works as expected.

### Demo
https://stackblitz.com/edit/ngx-infinite-scroll-bbaf6n

**Comment by orizens** [comment]
try setting height with px.

**Comment by alexandremoore** [comment]
@orizens, I know using px will work but I need to set it in %.

**Comment by orizens** [comment]
then try using ``height: 100vh``

**Comment by alexandremoore** [comment]
100vh does not equal 100%. I want 100% of the parent container which is not necessary 100% of the viewport.

**Comment by ThomasPizzo** [comment]
I am seeing it on window scroll as well when the html element is set to 100%. 

For example: html { height: 100% }

The scroll event never fires.

**Comment by orizens** [comment]
@alexandremoore @ThomasPizzo 
this should work:
```css
.search-results {
  height: 100%;
  display: flex;
  flex-direction: column;
}
```

**Comment by ck88ger** [comment]
your css code dont resolve this issue @orizens

**Comment by AlexandarVysotskiy** [comment]
With height: 100vh; also in working.
