### ISSUE TITLE
The callback does not trigger at all  (v6.0.1)

### ISSUE THREAD

**Issue by mvelebit** [orizens/ngx-infinite-scroll#300]
The following code simply fails to trigger the callback: 
```
<div infiniteScroll
     [infiniteScrollDistance]="1"
     [infiniteScrollUpDistance]="1.5"
     [infiniteScrollThrottle]="50"
     (scrolled)="loadMore()">
  <app-list></app-list>
</div>
```
The` loadMore()` method basically appends more divs into the `app-list` component, thus expanding this div. The result is basically alike any social media's homepage. The exact same setup works on v0.8.4 but doesn't work here. The css isn't appended as I actually have no css. Any clues? 

The only way I actually managed it to work (_at all_) was setting the div's height to a fixed value (**BUT LESS THAN 100vh**, for some reason, maybe I hadn't tested it thoroughly enough) and then setting the `[scrollWindow]="false" `, ending up with a small div with an infinite scroll inside it. 

This was hinting towards the `scrollWindow` failing altogether when it's set to true.

**Comment by vjscriv** [comment]
I am seeing the same behvaior. 

Thank you for finding and posting a work around mvelebit! Saved me from having to switch to something else.

**Comment by KobbyMmo** [comment]
mine is not working either, not even the workaround version (6.1.7)

**Comment by kodamirmo** [comment]
Hi guys, how do you solve this?

**Comment by orizens** [comment]
please reproduce on stackblitz
