### ISSUE TITLE
Use with ngx-perfect-scrollbar

### ISSUE THREAD

**Issue by Cuberice** [orizens/ngx-infinite-scroll#301]
Is it possible to use ngx-perfect-scrollbar with ngx-infinite-scroll?

**Comment by orizens** [comment]
Ngx infinite scroll listens to dom scroll event.
If the plugin you mention use a custom scroll event, then it wouldn't work.

**Comment by nomanbiniqbal** [comment]
+1

**Comment by guryanov-a** [comment]
@Cuberice @nomanbiniqbal @orizens 

it's possible:
1. apply `ngx-perfect-scrollbar` as a directive (see in docs how) on the same element as the `infinite-scroll` directive.
2. apply `[scrollWindow]="false"` option from `ngx-infinite-scroll` on the same element

Demo: https://stackblitz.com/edit/ngx-infinite-scroll-fw86eb
