### ISSUE TITLE
Support for Angular 7 virtual-scroll?

### ISSUE THREAD

**Issue by KartoffelToby** [orizens/ngx-infinite-scroll#302]
Any plans to intigrate the Angular 7 CDK Virtual Scroll?

**Comment by orizens** [comment]
a short answer - yes.
the long one: ngx-is takes the container height as a way to determine
whether a scroll event has been emitted (optimized) - will need to think of
another approach.


*Regards,Oren Farhi*
Founder at *Orizens.com* <http://orizens.com/>
Author of *Angular NgRx* <http://www.apress.com/us/book/9781484226193>*,*
Senior Front End Engineer & Consultant
*Front End Consulting Services* <http://orizens.com/services>

**Comment by dothem1337** [comment]
Any update on this enhancement? :)

**Comment by orizens** [comment]
@dothem1337 not yet.

**Comment by Lempkin** [comment]
Hi, is there any update about that? Thx =)

**Comment by orizens** [comment]
@Lempkin - unfortunately, no
