### ISSUE TITLE
Question| How i can show loading label/animation when end of scroll down?

### ISSUE THREAD

**Issue by ChenReuven** [orizens/ngx-infinite-scroll#304]
###Question:
How i can add a label of 'loading' at the end of each scroll when we load more items + re-render them on the screen (it can take a couple of second for a complex components iteration)

## Actual Behavior
Its nice to have feature for this infinity scroll :)

## Possible Solution
additional attribute that give u this option to the directive

Thanks,
Chen.R

**Comment by orizens** [comment]
hi.
you would have to handle it in your own way: listen to the scroll event, update the state of your component/app as "loading: true" - and render the "loading" label you want to have.
