### ISSUE TITLE
Can't bind to 'infiniteScrollDistance' since it isn't a known property of 'div' in angular version 7

### ISSUE THREAD

**Issue by banikKGP** [orizens/ngx-infinite-scroll#305]
Uncaught Error: Template parse errors:
**Can't bind to 'infiniteScrollDistance' since it isn't a known property of 'div'.** ("ia-label="Search files" />
        </div>

The following code which I have used:
`<div class="file-list folder-list" infiniteScroll [ERROR ->][infiniteScrollDistance]="8" [infiniteScrollThrottle]="50" (scrolled)="onScroll()">`

**Comment by kdmalviyan** [comment]
Facing same issue, @domessina  yes, I have included InfiniteScrollModule, in imports section of app.module.ts

**Comment by ZaidPathan** [comment]
Installing v10.x worked for me as my project Angular version is 12.x.
