### ISSUE TITLE
(scrolled) not fired on Windows scrolling

### ISSUE THREAD

**Issue by IrmaKarasoftic** [orizens/ngx-infinite-scroll#306]
Hi, I am using ngx-infinite-scroll with Angular 6. I can't get window scroll to work.
My issue is this:

```

<div class="outer-div">
   <div *ngFor="let item of items">
      //items
   </div>
   <div class="search-results" infiniteScroll 
   [infiniteScrollDistance]="0" 
   [infiniteScrollThrottle]="500"
   (scrolled)="onScroll()">
   </div>
</div>
```

When onScroll is triggered, new items are pushed in the items list.
I need .outer-div class to have {overflow-y: auto}. When I set overflow-y to auto, vertical scrollbar exists, but the onScroll() method isn't called. When I remove overflow-y: auto, it is set to default (visible), it works. But this is not what I need.
Can you tell me what am I doing wrong and why this doesn't work?

**Comment by SerjioH** [comment]
Same thing.

**Comment by orizens** [comment]
please edit the the issues's description using the [template](https://github.com/orizens/ngx-infinite-scroll/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by Dustinhoefer** [comment]
Did anyone find a solution yet? The whole project seems useless, now that scrolled and scrolledUp are not called at all.

**Comment by ganqqwerty** [comment]
can you please show your issue on stackblitz?
