### ISSUE TITLE
Re-initializing an infiniteScroll component cause (scrolled) to not fire

### ISSUE THREAD

**Issue by Avd6977** [orizens/ngx-infinite-scroll#308]
## Expected Behavior
Infinite Scroll container should trigger on scroll no matter how many times the component is destroyed and re-initialized.

## Actual Behavior
I have an Angular component that I want to be infinite scroll. On the first load, everything works perfectly fine. However, if I close that component (destroy it) and reopen it, the scroll event does not trigger. I've tried alwaysCallback and the this.infiniteScroll.ngOnDestroy() -> this.infiniteScroll.setup() method suggested in https://github.com/orizens/ngx-infinite-scroll/issues/294

### Context
I need to be able to open and close my Angular component frequently and always have the scroll bound and triggered properly

### Your Environment

- [ ] Version used: 6.0.1
- [ ] Browser Name and version: Chrome 70.0.3538.110
- [ ] (Optional) Operating System and version (desktop or mobile): Windows 10

**Comment by orizens** [comment]
please add a demo with stackblitz

**Comment by Avd6977** [comment]
Found the issue. There was a duplicate class elsewhere on the page so the infiniteScrollContainer wasn't binding right. Not sure why it worked the first time always and never the second time.

Closing.
