### ISSUE TITLE
how to use main scrollbar

### ISSUE THREAD

**Issue by anthowm** [orizens/ngx-infinite-scroll#314]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior

I guess is a question, I want only 1 scrollbard (main scrollbar like you have in echoesplayer, I check the code but I dont know how you make it to work like that)

## Actual Behavior

If I not use infiniteScrollContainer, (scrolled) never triggered. So I make it work with the container but I get two scrollbars like is normal.
![image](https://user-images.githubusercontent.com/5764698/51482525-f1c48980-1d96-11e9-8d72-08205e846f76.png)

### Steps To Reproduce / Demo (if applicable)
[ ] Please share a [stackblitz](https://stackblitz.com/) or [plunkr](https://plnkr.co/) demo reproducing this issue  
I'm using a fork of this project https://github.com/tomastrajan/angular-ngrx-material-starter
- I have a lazyloaded module with routes

PetComponent
```
<div [@routeAnimations]="o.isActivated && o.activatedRoute.routeConfig.path">
    <router-outlet #o="outlet"></router-outlet>
</div>
```

PetRoutes
```
{
    path: '',
    component: PetsComponent,
    children: [
      {
        path: '',
        component: PetListVirtualComponent,
        pathMatch: 'full',
        data: { title: 'pets.menu.petlist' },
        canActivate: [AuthGuardService],
      }
    ]
  }
```
PetListVirtualComponent
```
<div class="container mt-4 mb-4">
    <ng-container *ngIf="pets$ | async as pets; else loadingPets">
        <ng-container *ngIf="totalPets$ | async as totalPets; else loadingPets">
            <div class="container mt-4 mb-4 main-pets">
                <div class="row">
                    <h1 class="main-heading">{{ 'pets.list.title' | translate }} Virtual Version</h1>
                </div>
                <div infiniteScroll [infiniteScrollDistance]="2" [infiniteScrollThrottle]="50"
                    [infiniteScrollContainer]="'.main-pets'" [fromRoot]="true" (scrolled)="onScroll(pets.length, totalPets)">
                    <div class="row" [ngClass]="routeAnimationsElements">
                        <div class="col-12 col-md-6 col-lg-3" *ngFor="let pet of pets ; let index = index; trackBy: petsTrackByFn"
                            data-testid="pets-list">
                            <mat-card>
                                <a (click)="onViewPet(pet.id)">
                                    <mat-card-header>
                                        <mat-card-title>{{pet.name}}</mat-card-title>
                                        <mat-card-subtitle>{{pet.type}}</mat-card-subtitle>
                                    </mat-card-header>
                                    <img mat-card-image src="http://localhost:4000/{{pet.imageUrls[0].path}}" alt="Photo of a {{pet.name}}">
                                </a>
                                <mat-card-actions>
                                    <button mat-button [ngClass]="routeAnimationsElements">{{ 'pets.list.like' |
                                        translate
                                        |
                                        uppercase }}</button>
                                </mat-card-actions>
                            </mat-card>
                        </div>
                    </div>
                    <div *ngIf="loading && !empty" class="row justify-content-center">
                        <mat-spinner></mat-spinner>
                    </div>
                </div>
                <div class="row justify-content-center" *ngIf="empty">
                    <h3>Not more data!</h3>
                </div>
            </div>
        </ng-container>
    </ng-container>
    <ng-template #loadingPets>
        <div class="row justify-content-center">
            <mat-spinner></mat-spinner>
        </div>
    </ng-template>
    <div class="row justify-content-center">
        <div class="col-12 col-md-3">
            <button mat-raised-button color="primary" (click)="onCreatePet()" style="width:100%" [ngClass]="routeAnimationsElements"
                data-testid="pets-create-button">{{
                'pets.list.create' | translate }}</button>
        </div>
    </div>
</div>
```

CSS
```
.main-pets {
  height: 100vh;
  overflow-y: scroll;
}
```
### Your Environment

- [x] Version used: Angular 7
- [x] Browser Name and version: chrome
- [ ] (Optional) Operating System and version (desktop or mobile):
- [ ] (Optional) Link to your project: If is needed I can share you my repo 👍

**Comment by orizens** [comment]
seems like the cards container is assigned with a height - it shouldn't.

**Comment by anthowm** [comment]
If not use infiniteScrollContainer onScroll never triggered.
This is the only way it work with set height and overflow-y: scroll;
![image](https://user-images.githubusercontent.com/5764698/51485107-9053e900-1d9d-11e9-9c3e-be5307412ad5.png)

All the css of the component
```
img{
    height: 200px;
    background-position: 50% 50%;
    background-repeat:   no-repeat;
    background-size:     cover;
}

h1 {
  margin: 0 0 20px 0;
  text-transform: uppercase;
}

mat-card {
    margin: 0 0 10px 0;
    cursor: pointer;
  }
  
  .mat-fab {
    .fa-icon {
      position: relative;
      top: 4px;
    }
  }
  
  .add {
    margin: 20px auto 0;
    display: block;
  }

.main-pets {
  height: 100vh;
  overflow-y: scroll;
}
```

**Comment by orizens** [comment]
try using "forRoot" - so the scroll listens to the window (this is how it's
achieved in https://echoesplayer.com)

*Regards,Oren Farhi*
Founder at *Orizens.com* <http://orizens.com/>
Author of *Angular NgRx* <http://www.apress.com/us/book/9781484226193>*,*
Senior Front End Engineer & Consultant
*Front End Consulting Services* <http://orizens.com/services>

**Comment by anthowm** [comment]
I make it work 💃 thanks ! 
In case someone get someone like this, the problem is angular material add some style for scroll named '.mat-drawer-content' so my final code is like this
```
<div infiniteScroll [infiniteScrollDistance]="2" [infiniteScrollThrottle]="50" (scrolled)="onScroll(pets.length, totalPets)"
                    [infiniteScrollContainer]="'.mat-drawer-content'" [fromRoot]="true">{content}</div>
```

**Comment by shrishail-smartlybuilt** [comment]
> I make it work 💃 thanks !
> In case someone get someone like this, the problem is angular material add some style for scroll named '.mat-drawer-content' so my final code is like this
> 
> ```
> <div infiniteScroll [infiniteScrollDistance]="2" [infiniteScrollThrottle]="50" (scrolled)="onScroll(pets.length, totalPets)"
>                     [infiniteScrollContainer]="'.mat-drawer-content'" [fromRoot]="true">{content}</div>
> ```

This is not working now. mat-drawer-content is getting created after the error **ngx-infinite-scroll {resolveContainerElement()}: selector for**

**Comment by rajat29gupta** [comment]
>  [fromRoot]="true"

Thank you so much, It work for me :)
 I was stuck for 5 hours on this issue

**Comment by rajat29gupta** [comment]
> I make it work 💃 thanks !
> In case someone get someone like this, the problem is angular material add some style for scroll named '.mat-drawer-content' so my final code is like this
> 
> ```
> <div infiniteScroll [infiniteScrollDistance]="2" [infiniteScrollThrottle]="50" (scrolled)="onScroll(pets.length, totalPets)"
>                     [infiniteScrollContainer]="'.mat-drawer-content'" [fromRoot]="true">{content}</div>
> ```

It is not working for mobile view. Can you please help me out
