### ISSUE TITLE
Can we have a bugfix release for Angular6?

### ISSUE THREAD

**Issue by Nas3nmann** [orizens/ngx-infinite-scroll#329]
This pull request fixed an issue with the postinstall script of opencollective: https://github.com/orizens/ngx-infinite-scroll/pull/321

Can we have a bugfix release 6.0.2 for angular 6 support? 
We love the infinite scroll table, but Jenkins builds are failing quite often due to this error.

**Comment by orizens** [comment]
i see conflicts

**Comment by jwedel** [comment]
@orizens yes, I commented on the PR why there are conflicts. please have a look.

**Comment by orizens** [comment]
i was able to publish a new 6.9.1 at
https://www.npmjs.com/package/ngx-infinite-scroll/v/6.9.1
branch is available on branch https://github.com/orizens/ngx-infinite-scroll/tree/fix/ng-6

**Comment by jwedel** [comment]
👍🥳
