### ISSUE TITLE
ScrollUp from the beginning of the list

### ISSUE THREAD

**Issue by nicotv** [orizens/ngx-infinite-scroll#331]
Hello,

I use 7.2v. 

The scrollup does not work from the beginning of the list. First you have to do a scrolldown.

Moreover, if we scroll up too quickly, it freezes. :(

example : https://stackblitz.com/edit/ngx-infinite-scroll

Do you have an idea?

Thank you so much

**Comment by jlandsmann** [comment]
Same problem here

**Comment by MarcoLaws** [comment]
Same.

I try by prepending datas in the list but if we are in top of list, we keep positioning at the top instead of keep position of the current item.
See my comment in other issue #334 [my comment](https://github.com/orizens/ngx-infinite-scroll/issues/334#issuecomment-824814093)

**Comment by alejandrB000** [comment]
+1
