### ISSUE TITLE
how can i do reverse scrolling ?

### ISSUE THREAD

**Issue by kevit-sunny-anuvadiya** [orizens/ngx-infinite-scroll#338]
how can i do reverse scrolling , like from last item of scroll to top item like chat app?

**Comment by radiumrasheed** [comment]
did anyone figure this out?

**Comment by DaltonKeightley** [comment]
Checking if anyone's figured this out yet

**Comment by rashalismath2** [comment]
use scrolledUp event instead of scrolled
![image](https://github.com/orizens/ngx-infinite-scroll/assets/51192191/19d87a68-52a5-47cb-8452-d8f9c4e24d2b)
![image](https://github.com/orizens/ngx-infinite-scroll/assets/51192191/87978697-81a3-4f39-8378-b7899610bec0)
