### ISSUE TITLE
how to use infiniteScrollDistance? scrolled event fires no matter what value

### ISSUE THREAD

**Issue by henryyue2010** [orizens/ngx-infinite-scroll#339]
I followed the example. 
```
<div
      class="search-results"
      infiniteScroll
      [infiniteScrollDistance]="2"
      [infiniteScrollThrottle]="50"
      (scrolled)="onScroll()"
    ></div>
```
but the scrolled event fires right after the page scrolls, no matter the value of infiniteScrollDistance.
How to make it work?
Thank you very much in advance for your help.

## Expected Behavior

Scrolled to the expected position, then the scrolled event fires.

## Actual Behavior

the scrolled event fires right after the page scrolls.

### Steps To Reproduce / Demo (if applicable)
[ ] Please share a [stackblitz](https://stackblitz.com/) or [plunkr](https://plnkr.co/) demo reproducing this issue  

### Your Environment

- [ ] Version used: 
- [ ] Browser Name and version:
- [ ] (Optional) Operating System and version (desktop or mobile):
- [ ] (Optional) Link to your project:

**Comment by orizens** [comment]
infiniteScrollDistance is sensitive -  try out the demo.
