### ISSUE TITLE
Allow scroll distance to be calculated on fixed height instead of % of height

### ISSUE THREAD

**Issue by Humberd** [orizens/ngx-infinite-scroll#340]
The problem is that when I keep scrolling down the more items is added to the scroll element and and the less I have to scroll again to reach the `infiniteScrollDistance` threshold.

For example:

1st set of data -> I have to scroll 20 full wheels.
2nd set of data -> I have to scroll 15 full wheels.
3rd set of data -> I have to scroll 10 full wheels.

And it keeps getting lower and lower, so at the page 10 only a couple of scrolls would be sufficient to trigger the scroller. This is highly inefficient.

**Comment by DarkMerge** [comment]
+

**Comment by ranetpgit** [comment]
Support. Would like to set a fixed/px value for the trigger as well. The library is really great, and it would be pretty much perfect, if this were to be resolved.
