### ISSUE TITLE
ERROR TypeError: Cannot read property 'offsetWidth' of undefined

### ISSUE THREAD

**Issue by godhand1607** [orizens/ngx-infinite-scroll#345]
## Environment
- Ionic 4 + Angular 8
- Using v8.0.1
- Prod build

## Description
- I'm currently getting this error when running the app with angular cli's prod settings
<img width="1002" alt="Screen Shot 2020-01-15 at 2 27 53 AM" src="https://user-images.githubusercontent.com/7845870/72371275-fcfa8d00-373e-11ea-809b-b6a1b9fe044f.png">

- Did a little bit of debugging and the `resolver` obj doesn't contain a `container` prop while when running on prod settings, it only has `nativeElement`

Wondering if anyone encountered this issue before?

**Comment by orizens** [comment]
Can you share a codesandbox or other that reproduce the issue?
Previously, there were issues with ionic.

**Comment by godhand1607** [comment]
Figured out the issue was. It was the angular compiler's fault, the `createScroller` function is stripped out during compilation. Was able to fix it by upgrading angular dependencies.
