### ISSUE TITLE
ngx-infinite-scroll is not working from seconds scroll

### ISSUE THREAD

**Issue by eldhose-cavli** [orizens/ngx-infinite-scroll#347]
`<div class="search-results" infiniteScroll  
          [infiniteScrollDistance]="2"
          [infiniteScrollThrottle]="50" 
          [fromRoot]="false"
          (scrolled)="onScroll()"> 
              <button  *ngFor="let data of result " >
              </button>
          </div>`

**Comment by janakiram-madurai** [comment]
Hi how u resolved this issue?

**Comment by eldhose-cavli** [comment]
<div class="search-results" style="height:100%;overflow-y:auto;" infiniteScroll  
          [infiniteScrollDistance]="2"
          [infiniteScrollThrottle]="50" 
          [fromRoot]="false"
          [scrollWindow]="false"
          (scrolled)="onScroll()"> 
              <button   *ngFor="let item of List ; trackBy:trackByFn" > </button>
          </div>

**Comment by janakiram-madurai** [comment]
Adding the style resolved your issue?
