### ISSUE TITLE
ScrollDown event not firing in the Windows10 Chrome(Angular v 8, ngx version :8.0.0)

### ISSUE THREAD

**Issue by seethadevi** [orizens/ngx-infinite-scroll#348]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

### Steps To Reproduce / Demo (if applicable)
[ ] Please share a [stackblitz](https://stackblitz.com/) or [plunkr](https://plnkr.co/) demo reproducing this issue  

### Your Environment

- [ ] Version used: 
- [ ] Browser Name and version:
- [ ] (Optional) Operating System and version (desktop or mobile):
- [ ] (Optional) Link to your project:

**Comment by thaissarojas** [comment]
Hi, i am having the same problem, but in linux, and with any browser. It's just not working on angular 8? It works just fine on angular 11

**Comment by dhruvi7489** [comment]
I'm facing this same problem with **scrolled** event not firing in windows 10 & 11 and i'm using angular 8.3.29 and "ngx-infinite-scroll": "^8.0.2", is there any specific solution for it?
