### ISSUE TITLE
Common config

### ISSUE THREAD

**Issue by aharadkou** [orizens/ngx-infinite-scroll#349]
Is it possible to create common config overriding default values of directive properties([infiniteScrollDistance], [infiniteScrollThrottle])?

**Comment by andreash92** [comment]
would love to know about this also

**Comment by orizens** [comment]
@aharadkou can you provide an example of a common config?

**Comment by aharadkou** [comment]
> @aharadkou can you provide an example of a common config?
In my view it should look smth like this:
```AppModule.ts
@NgModule({
  ...
  providers: [
    {
      provide: SCROLL_CONFIG,
      useValue: {
        infiniteScrollDistance: 1.5,
        infiniteScrollThrottle: 250,
        scrollWindow: false
     }
    }
  ]
})
```
Then value provided with SCROLL_CONFIG token should be used to set default `@Input()` properties for all infiniteScroll instances

**Comment by orizens** [comment]
@aharadkou it can help if you can link another library/component that implements

**Comment by aharadkou** [comment]
> @aharadkou it can help if you can link another library/component that implements

@orizens Perfect scrollbar implements it https://www.npmjs.com/package/ngx-perfect-scrollbar
