### ISSUE TITLE
Update roll up external and global for rxjs/operators to infer correct UMD module identifier

### ISSUE THREAD

**Issue by frozenplanet14** [orizens/ngx-infinite-scroll#350]
Currently roll up is guessing the module id for rxjs/operator as rxjs_operators, while the rxjs exposes it as rxjs.operators. Is it possible to update the roll up config as below:

`
external: [
      '@angular/core',
      '@angular/common',
      'rxjs',
      'rxjs/Observable',
      'rxjs/Observer',
      'rxjs/operators'
    ],
  globals: {
    '@angular/core': 'ng.core',
    '@angular/common': 'ng.common',
    rxjs: 'rxjs',
    'rxjs/Observable': 'Rx',
    'rxjs/Observer': 'Rx',
    'rxjs/operators': 'rxjs.operators'
  }`

Your issue may already be reported!
Please search on the [issue track](../) before creating one.

### Steps To Reproduce / Demo (if applicable)
[ ] Please share a [stackblitz](https://stackblitz.com/) or [plunkr](https://plnkr.co/) demo reproducing this issue  

### Your Environment

- [ ] Version used: 
- [ ] Browser Name and version:
- [ ] (Optional) Operating System and version (desktop or mobile):
- [ ] (Optional) Link to your project:

**Comment by orizens** [comment]
version 9 has been released.
@frozenplanet14 please update and close if not relevant anymore

**Comment by frozenplanet14** [comment]
Rollup config is missing the rxjs operator from the list with the latest one as well. It is possible to update it as below? Please let me know if that is not possible, I will close this issue.

```typescript
export default {
    entry: './dist/modules/ngx-infinite-scroll.es5.js',
    dest: './dist/bundles/ngx-infinite-scroll.umd.js',
    format: 'umd',
    exports: 'named',
    moduleName: 'ng.ngxInfiniteScroll',
    external: [
        '@angular/core',
        '@angular/common',
        'rxjs',
        'rxjs/Observable',
        'rxjs/Observer',
        'rxjs/operators'
    ],
    globals: {
        '@angular/core': 'ng.core',
        '@angular/common': 'ng.common',
        rxjs: 'rxjs',
        'rxjs/Observable': 'Rx',
        'rxjs/Observer': 'Rx',
        'rxjs/operators': 'rxjs.operators'
    },
    onwarn: () => { return }
}
```

**Comment by orizens** [comment]
@frozenplanet14 please feel free to open a pr and add that.

**Comment by frozenplanet14** [comment]
Thanks @orizens! PR https://github.com/orizens/ngx-infinite-scroll/pull/357 has been submitted for review.
