### ISSUE TITLE
make [scrollWindow]="false" by default

### ISSUE THREAD

**Issue by ghost** [orizens/ngx-infinite-scroll#354]
## Expected Behavior
**suggestion/improvement**
I think, mostly we use infinite-scroll directive, we want to listen exactly on this element not on the window object itself, so it would be better to be like this by default, and not adding `[scrollWindow]="false"` every time

## Actual Behavior
By default, it is attached to the window object

## Possible Solution

- By default, it is not attached to the window object
- if the first option is a too big breaking change, we could add some global config, that will define default properties

### Steps To Reproduce / Demo (if applicable)
[ ] Please share a [stackblitz](https://stackblitz.com/) or [plunkr](https://plnkr.co/) demo reproducing this issue  

### Your Environment

- [ ] Version used: 
- [ ] Browser Name and version:
- [ ] (Optional) Operating System and version (desktop or mobile):
- [ ] (Optional) Link to your project:

**Comment by FredUK** [comment]
Ah! You helped me solve the problem I was having for the past 30 minutes ..I just couldn't figure out why my (scroll) event wasn't triggering at all.. That was the reason :+1:

**Comment by orizens** [comment]
@lukaonik that would be a breaking change for millions of projects that are using ngxis.
i can think of exporting a second component which would set that value to false by default.
i'm suggesting:
```html
<ngx-infinite-scroll-container />
```

**Comment by orizens** [comment]
@lukaonik try out
ngx-infinite-scroll@10.0.9-next
with the above component:
```html
<ngx-infinite-scroll-container
      infiniteScroll
      [infiniteScrollDistance]="scrollDistance"
      [infiniteScrollUpDistance]="scrollUpDistance"
      [infiniteScrollThrottle]="throttle"
      (scrolled)="onScrollDown()"
      (scrolledUp)="onUp()"
    >
<generate-scrollable-content-here />
</ngx-infinite-scroll-container>
```
also - please set the infinite-scroll element class with a height:
```css
.ngxisc {
  height: 300px;
  overflow: auto;
}
```
