### ISSUE TITLE
Production build produces unwanted console logs.

### ISSUE THREAD

**Issue by AlexA-1976** [orizens/ngx-infinite-scroll#356]
## Expected Behavior
No console logging should happen unless I explicitly put it there.

## Actual Behavior
Every scroll-down this appears in the console log. On debug build, it doesn't happen.

**(2)
 [{…}, {…}]
0: {contentHeight: undefined, scrolledFromTop: undefined, viewportHeight: undefined}
1: {contentHeight: undefined, scrolledFromTop: undefined, viewportHeight: undefined}
length: 2__
proto__: Array(0)**

### Steps To Reproduce / Demo (if applicable)
Using 'infiniteScroll' on a ul element. Scrolling behavior works.

### Your Environment
    "ngx-infinite-scroll": "^6.0.0",
    "@angular/core": "6.1.10",

**Comment by orizens** [comment]
hi @AlexA-1976 if you open a pr for v6 - i can publish it as next 6.

**Comment by AlexA-1976** [comment]
@orizens I looked in the source just now and couldn't find any console.log() calls. Is it possible some lower level library is doing this?

**Comment by orizens** [comment]
might be.
you would have to look into a commit from v6.

**Comment by orizens** [comment]
checkout this commit https://github.com/orizens/ngx-infinite-scroll/tree/fa01a048a7f98bcf42ac883051318f04f9e5baf0

**Comment by VikasKad** [comment]
Is there any update on this issue? I am still getting this error.
 My environment details are as follows:
    "@angular/core": "^6.0.0",
    "ngx-infinite-scroll": "^6.0.0",

**Comment by orizens** [comment]
@VikasKad i dont see any pr for version 6.

**Comment by VikasKad** [comment]
> checkout this commit https://github.com/orizens/ngx-infinite-scroll/tree/fa01a048a7f98bcf42ac883051318f04f9e5baf0

 I Checked in this commit, but I didn't find any console.log in it as well.
