### ISSUE TITLE
what is the issue with 08-infinite-scroll-example

### ISSUE THREAD

**Issue by NitinMagdum** [orizens/ngx-infinite-scroll#358]
i am using this plugin for infinite scroll and search functionality but its not working. check 08 example from below link

https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example?spm=a2c6h.14275010.0.0.4843743e0qwXH3&file=src%2Fapp%2Fapp.component.html

## Expected Behavior
when we scroll till the bottom it should load next set of 20 records(limit is 20 so it should show total 40 recors and so on), 

## Actual Behavior
next set of data is not getting loaded on scroll - i think it is not calling getNextBatch method

**Comment by orizens** [comment]
it's not relates to ngx-infinite-scroll
