### ISSUE TITLE
Unable to install package when run - npm install ngx-infinite-scroll --save

### ISSUE THREAD

**Issue by Moshe1988** [orizens/ngx-infinite-scroll#360]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@scarf%2fscarf - Not found
npm ERR! 404 
npm ERR! 404  '@scarf/scarf@0.1.5' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'ngx-infinite-scroll'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/usr/.npm/_logs/2020-08-06T09_59_37_700Z-debug.log

**Comment by romach** [comment]
@Moshe1988 I think this error is emerged because of NPM incident https://status.npmjs.org/incidents/cksjqc1w11v5
