### ISSUE TITLE
Global configuration: Change default values in module

### ISSUE THREAD

**Issue by ahadjithoma** [orizens/ngx-infinite-scroll#362]
Is there any way to set the default values in module where the InfiniteScrollModule is imported? 

Scenario: 
I want all the pages with scroll to fetch the next page when the user is on the half page. It would be very useful if I could to set the `infiniteScrollDistance` to 5 only once

**Comment by orizens** [comment]
hi @ahadjithoma 
you can create a component that wraps ngxis and set the value to 5.
```html
<my-infinite />
```
