### ISSUE TITLE
Angular 10 compatibility

### ISSUE THREAD

**Issue by bisonfoutu** [orizens/ngx-infinite-scroll#365]
## Actual Behavior

The Readme indicates that this lib now follows Angular versions to reflect compatibility.
There is currently no available 10.X.X version for ngx-infinite-scroll, suggesting that the library is not compatible with Angular 10.

## Possible Solution

If the library is already compatible, consider bumping the version to 10.0.0.
If not, I would be happy to help make it so !

### Context

I am considering upgrading my apps to Angular 10, and before doing so I would like to be sure that all my dependencies are compatible.

**Comment by slcoder** [comment]
Hello, this library is not compatible with angular 10, I tried to integrate this with my latest application (Angular 10), doesn't work. Please, anyone, take a look at this?

**Comment by bisonfoutu** [comment]
@slcoder I just made this [simple working example](https://stackblitz.com/edit/ngx-infinite-scroll-910-ng10?devtoolsheight=33&file=src/app/app.component.html) using Angular 10 and ngx-infinite-scroll@9.1.0: 
Obviously this does not cover all use cases, so feel free to link a repo to illustrate your own use case.

@orizens do you plan to address this any time soon ? I'd gladly raise a PR but will probably need your assistance.

**Comment by slcoder** [comment]
> @slcoder I just made this [simple working example](https://stackblitz.com/edit/ngx-infinite-scroll-910-ng10?devtoolsheight=33&file=src/app/app.component.html) using Angular 10 and ngx-infinite-scroll@9.1.0:
> Obviously this does not cover all use cases, so feel free to link a repo to illustrate your own use case.
> 
> @orizens do you plan to address this any time soon ? I'd gladly raise a PR but will probably need your assistance.

Thank you very much, let me try this

**Comment by orizens** [comment]
> @slcoder I just made this [simple working example](https://stackblitz.com/edit/ngx-infinite-scroll-910-ng10?devtoolsheight=33&file=src/app/app.component.html) using Angular 10 and ngx-infinite-scroll@9.1.0:
> Obviously this does not cover all use cases, so feel free to link a repo to illustrate your own use case.
> 
> @orizens do you plan to address this any time soon ? I'd gladly raise a PR but will probably need your assistance.

Sure. Please do

**Comment by abdatta** [comment]
Is anybody working on this? If not I'll raise a PR soon.

**Comment by bisonfoutu** [comment]
@abdatta please do, I will probably not have time to do this in the next few days.

**Comment by orizens** [comment]
v10 released.
