### ISSUE TITLE
Scroll Event Not Triggering

### ISSUE THREAD

**Issue by anurag2pirad** [orizens/ngx-infinite-scroll#367]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behaviour

Scroll event should get triggered.

## Actual Behaviour

Not triggering.

## Possible Solution

The component in which I'm trying this out is a lazy loaded module if that helps.

### Steps To Reproduce / Demo (if applicable)
[ ] Please share a [stackblitz](https://stackblitz.com/) or [plunkr](https://plnkr.co/) demo reproducing this issue  
I just used the code provided in your README demo, but still it did not work.

### Context

Cannot understand why this is not working. Any help will be appreciated.

### Your Environment

- [x] Version used: 9.1.1 (angular), 9.1.0 (ngx-infinite-scroll)
- [x] Browser Name and version: Chrome 85.0.4183.121 (Official Build) (64-bit)
- [x] (Optional) Operating System and version (desktop or mobile): MacOS Catalina 10.15.7 (19H2)
- [ ] (Optional) Link to your project:

**Comment by JamesonNetworks** [comment]
check out https://github.com/orizens/ngx-infinite-scroll/issues/354 , may be your issue

**Comment by orizens** [comment]
closed for lack of activity.
