### ISSUE TITLE
Output scrolled not working?

### ISSUE THREAD

**Issue by MinhPhuPham** [orizens/ngx-infinite-scroll#370]
## Actual Behavior
In My company project, i using infinite-scroll with [DropDown](https://ng-bootstrap.github.io/#/components/dropdown/examples)  and dynamic components but when closed dropdown, the event output Scrolled not working. 

Its maybe because when open again dropdown, i destroy old componentRef? how i can fix in here?

## Information Support
![image](https://user-images.githubusercontent.com/51711158/99089182-8f89e800-25ff-11eb-8fb3-5cf29038de28.png)
HTML code
![image](https://user-images.githubusercontent.com/51711158/99089230-9add1380-25ff-11eb-8935-870b1d880eaa.png)
![image](https://user-images.githubusercontent.com/51711158/99089248-a03a5e00-25ff-11eb-818d-378759f8b2d3.png)
![image](https://user-images.githubusercontent.com/51711158/99089338-bcd69600-25ff-11eb-818d-14cc1be898c1.png)
ts code 
And in dynamic components a using router navigate when click card.

My email is: phamminhphueur@gmail.com.
Thanks for support this, hope it will thrive more.

### Your Environment

- [x] Version used: Angular 9.1.12
- [x] Browser Name and version: Chrome Lastest Version
- [ ] (Optional) Operating System and version (desktop or mobile):
- [ ] (Optional) Link to your project:

**Comment by MinhPhuPham** [comment]
can anyone help me?

**Comment by harveyelsisura** [comment]
I guess it is not working anymore

**Comment by MinhPhuPham** [comment]
So sad for that, i have used virtual scroll CDK for fix this case

**Comment by orizens** [comment]
@MinhPhuPham if you can reproduce the issue that can be helpful.
