### ISSUE TITLE
First Scroll of a Small Infinite-Scroll

### ISSUE THREAD

**Issue by AmirhosseinSA** [orizens/ngx-infinite-scroll#371]
I am trying to implement a scrollbar that has paging capabilities. Everything works well and I am able to add elements to my div when the scrollbar reaches near the bottom. But there is a problem when there are very few initial elements in my div (enough to fit inside the div without needing a scrollbar) and the scrollbar events do not work at all. What should I do?

**Comment by orizens** [comment]
you should load more items and flip the "disable" property after loading - so ngxis recreates.
