### ISSUE TITLE
Infinit Upscrolling not working in Firefox

### ISSUE THREAD

**Issue by horenso** [orizens/ngx-infinite-scroll#376]
Hello :)
I love this project so far, but I am having some issues with it in Firefox.

Infinite scrolling-up doesn't bounce back on Firefox 84, even when I open the demo in Chrome and Firefox, scrolling-up doesn't work in Firefox but works fine in Chrome.

Here is it in our project:
https://www.dropbox.com/s/4okfsbanfj2xlfg/output.gif?dl=0

Here is my configuration:

```
<div infiniteScroll
   [infiniteScrollUpDistance]="2"
   [infiniteScrollThrottle]="50"
   [alwaysCallback]=false
   [scrollWindow]=false
   (scrolledUp)="onScroll()">
...
</div>
```

I didn't create a live demo, because it even happens in the demo. This is really annoying since my project needs no to be compatible with Firefox.

### Your Environment

- Version used:  10.0.1 (Angular version 10.2.0) 
- Browser Name and version: Firefox 84.0.2 (negative) and Chrome 87.0.4280.141 (works)
- (Optional) Operating System and version (desktop or mobile): Linux Mint 20
- (Optional) Link to your project: not public (yet maybe)

**Comment by BarkhatovN** [comment]
It could probably clarify something to solve issue 

https://github.com/orizens/ngx-infinite-scroll/issues/373#issuecomment-770208622
