### ISSUE TITLE
ngx-infinite-scroll {resolveContainerElement()}: selector for

### ISSUE THREAD

**Issue by dougse** [orizens/ngx-infinite-scroll#380]
With version 8.0.2, I encounter:

Error: ngx-infinite-scroll {resolveContainerElement()}: selector for
    at resolveContainerElement (ngx-ins-utils.ts:18)
    at createScroller (scroll-register.ts:16)
    at infinite-scroll.directive.ts:66
    at ZoneDelegate.invoke (zone.js:386)
    at Zone.run (zone.js:143)
    at NgZone.runOutsideAngular (core.js:28464)
    at InfiniteScrollDirective.setup (infinite-scroll.directive.ts:65)
    at InfiniteScrollDirective.ngAfterViewInit (infinite-scroll.directive.ts:44)
    at callHook (core.js:2521)
    at callHooks (core.js:2492)

Which then results in angular failing to render the page and/or some repositioning issues.

Tips please - Thanks

**Comment by meyer20** [comment]
I'm having this problem when running the tests.

"jest": "^26.6.3",

My implementation:
<div class="card-columns"
     infiniteScroll
     [infiniteScrollDistance]="1"
     [infiniteScrollThrottle]="50"
     (scrolled)="onScroll()"
     [infiniteScrollContainer]="'.parent-container'"
     [fromRoot]="true"
     [hidden]="isLoading">
</div>

**Comment by osamamalik2000** [comment]
What I found is that it is somehow not able to find  [infiniteScrollContainer]="'.parent-container'"  so it is throwing this error. I somehow managed to use scroll without this function.

**Comment by mahdizarei0614** [comment]
You can pass the `elementRef` to `infiniteScrollContainer`:
`
<div #containerRef style="height: 100vh; overflow-y: auto;">
  <div infiniteScroll
       [infiniteScrollDistance]="2"
       [infiniteScrollThrottle]="50"
       [infiniteScrollContainer]="containerRef">
  </div>
</div>
`
- Notice that in the container element `height` must be fixed and the overflow must be `auto` or `scroll`.

**Comment by mahdizarei0614** [comment]
You can pass the `ElementRef` type to `infiniteScrollContainer`:
```
<div #containerRef style="height: 100vh; overflow-y: auto;">
  <div infiniteScroll
       [infiniteScrollDistance]="2"
       [infiniteScrollThrottle]="50"
       [infiniteScrollContainer]="containerRef">
  </div>
</div>
```
- Notice that in the container element `height` must be fixed and the overflow must be `auto` or `scroll`.

**Comment by mahdizarei0614** [comment]
You can pass the `ElementRef` type to `infiniteScrollContainer`:
```
<div #containerRef style="height: 100vh; overflow-y: auto;">
  <div infiniteScroll
       [infiniteScrollDistance]="2"
       [infiniteScrollThrottle]="50"
       [infiniteScrollContainer]="containerRef">
  </div>
</div>
```
- Notice that in the container element `height` must be fixed and the overflow must be set to `auto` or `scroll`.

**Comment by nirajdgrooar** [comment]
> You can pass the `ElementRef` type to `infiniteScrollContainer`:
> 
> ```
> <div #containerRef style="height: 100vh; overflow-y: auto;">
>   <div infiniteScroll
>        [infiniteScrollDistance]="2"
>        [infiniteScrollThrottle]="50"
>        [infiniteScrollContainer]="containerRef">
>   </div>
> </div>
> ```
> 
> * Notice that in the container element `height` must be fixed and the overflow must be set to `auto` or `scroll`.

This worked for me Thanks a lot
