### ISSUE TITLE
Infinite scroll down on firefox position scroll on top after fired event

### ISSUE THREAD

**Issue by flucciarini** [orizens/ngx-infinite-scroll#383]
Hi Everyone
I'm having an issue when use the component in firefox browser. After fire the onScroll event the scroll position reset on top.
Working well on Chrome.

In my site I load the content of page dinamically and so I use infinite scroll as paginator to load next page's data and append it on bottom of page 

.html file
<div class="maincontent" infiniteScroll [scrollWindow]="true" [infiniteScrollDistance]="2"
  [infiniteScrollThrottle]="500" (scrolled)="onScroll()">

.ts file
onScroll() {
    console.log('INFINITE SCROLL');
    if (this.canLoadMore()) {  //check to prevent multiple load
      this.loadMore(); //start load 
    }
  }

Have anyone this same issue?

- [ ] Version used: 9.1.0
- [ ] Browser Name and version: Firefox 89.0 (64bit)
- [ ] (Optional) Operating System and version (desktop or mobile): windows 10

**Comment by mattveraldi** [comment]
I have the same problem with MS Edge

**Comment by Jannyboy313** [comment]
I have the same problem with chrome

**Comment by Cjoshua2** [comment]
I had the same problem, turns out my input tag has the focus attribute after I used it. Had to use the .blur() to remove it once the search is done.

Sorry for my english.
