### ISSUE TITLE
Angular 12 Support

### ISSUE THREAD

**Issue by m-khnarges** [orizens/ngx-infinite-scroll#384]
Hi,
Does the package works correctly with Angular 12?
In my project, some of inputs like infiniteScrollDisabled or infiniteScrollDistance do not have any impacts and scroll function always called immediately.

- [ ] Version used: 10.0.1
- [ ] Browser Name and version: Chrome 92
- [ ] (Optional) Operating System and version (desktop or mobile): Mac OS

**Comment by orizens** [comment]
hi @m-khnarges version 13 has been released to npm.

**Comment by m-khnarges** [comment]
Thank you so much, It's been corrected.
