### ISSUE TITLE
Scroll event not fired when scrolling fast to the bottom

### ISSUE THREAD

**Issue by barisbikmaz** [orizens/ngx-infinite-scroll#385]
## Expected Behavior
When I scroll to the bottom of a list the "scroll" event should be fired.

## Actual Behavior
When I have e.g. infiniteScrollThrottle =500 defined I scroll fast to the bottom of a list the scroll event is not fired.

## Possible Solution
Possible solution is to set infiniteScrollThrottle=0.
Root causee seems to be the change from sampleTime to throttleTime. ThrottleTime does fire on next scroll but when you scroll to the bottom there is no next scroll.

### Steps To Reproduce / Demo (if applicable)
![Scroll Problem](https://user-images.githubusercontent.com/6338132/130756146-bd7dee5f-3e7a-4e5f-aa59-76081cb3631b.gif)

### Your Environment
- [x] Version used: 10.0.1
- [x] Browser Name and version: Chrome 92.x
- [x] (Optional) Operating System and version (desktop or mobile): Windows 10 Desktop

**Comment by DonutLaser** [comment]
I'm experiencing this as well

**Comment by KelSmile** [comment]
I have the same problem.
It is the same for the up scroll.

**Comment by KelSmile** [comment]
> Root causee seems to be the change from sampleTime to throttleTime. ThrottleTime does fire on next scroll but when you scroll to the bottom there is no next scroll.
> 
I found the same conclusion.
Maybe setting the trailing attribute from throttleTime to true, could help here.

Idea: https://stackoverflow.com/questions/37146081/rxjs-throttle-behavior-get-first-value-immediately

**Comment by RifkyLTF** [comment]
I was having the same issue. Adding `[infiniteScrollThrottle]="0"` will fix the problem but you need to handle your load more function carefully because scrolled event will trigger instantly without having to wait user stopped scrolling. kindly check [supported API](https://github.com/orizens/ngx-infinite-scroll#supported-api)

**Comment by naveedahmed1** [comment]
In my case the http requests gets cancelled when I scroll too fast, any help would be appreciated.

**Comment by orizens** [comment]
all, version 13 has been released.
please feel free to create a pr for this.

**Comment by sagrawal31** [comment]
Upgrading to v13 of this library fixes the issue 👏🏻
