### ISSUE TITLE
Upgrade to angular 13 + Ivy

### ISSUE THREAD

**Issue by POFerro** [orizens/ngx-infinite-scroll#390]
Hi :),

Are there any plans to upgrade this library to support angular 13 and Ivy compilation?

Thanks and best regards
POFerro

**Comment by orizens** [comment]
i'm accepting pr's.

**Comment by maxime1992** [comment]
Hello, thanks for the library!

Good to know you're accepting PR's. I've taken that opportunity to raise one in order to [bring support for Angular 13](https://github.com/orizens/ngx-infinite-scroll/pull/392)

**Comment by siddharth1903** [comment]
@orizens I see a next tag being published for ng 13... Any reason why this is not the latest? If there are issues, i can take this up and create a new PR !

**Comment by orizens** [comment]
@siddharth1903 @maxime1992  will post a branch soon to add Angular 13

**Comment by pokermanx** [comment]
Progress on this?

**Comment by dzena** [comment]
@orizens If you feel like you need additional pair of eyes on Angular v13 PR I think I can find some tome to review it and run some tests as well.
Feel free to ping me anytime. 
Thank you for maintaining and pushing this lib forward. 👏

**Comment by orizens** [comment]
Hi all - @siddharth1903 @maxime1992 @pokermanx @dzena @POFerro 
version 13.0.1 has been pushed to npmjs and to master.
Please feel free to contribute, suggest changes and much more in pr's
