### ISSUE TITLE
Implementing Recycling Virtual Scroll - Feature Request

### ISSUE THREAD

**Issue by futurbotconsolidated** [orizens/ngx-infinite-scroll#393]
Hi! Team

The best approach to save app from memory leak is to use recycler list view. We have <cdk-virtual-scroll-viewport> in angular material. 

Can we implement this feature in this? I am happy to contribute if you guys are ready to work together.

https://material.angular.io/cdk/scrolling/overview

**Comment by orizens** [comment]
version 13 has been released.
please feel free to open a pr.

**Comment by futurbotconsolidated** [comment]
> version 13 has been released. please feel free to open a pr.

Hi! @orizens Can you please specify somewhere about what's new in v13?

**Comment by orizens** [comment]
mostly ng version upgrade https://github.com/orizens/ngx-infinite-scroll/blob/master/projects/ngx-infinite-scroll/CHANGELOG.md
