### ISSUE TITLE
Are you still maintaining this library?

### ISSUE THREAD

**Issue by SebastianStehle** [orizens/ngx-infinite-scroll#415]
I like the library and as of now, it is the only component that supports flexible item heights. It is really great. 

But it is sad that it is not maintained anymore. What is the current status?

**Comment by orizens** [comment]
hey @SebastianStehle 
I'm still accepting prs

**Comment by SebastianStehle** [comment]
I am so stupid. This is the wrong repository :D ... I was meaning ngx-virtual-scroller
