### ISSUE TITLE
error NG6002: 'InfiniteScrollModule' does not appear to be an NgModule class.

### ISSUE THREAD

**Issue by didemchenko** [orizens/ngx-infinite-scroll#421]
Angular/nfiniteScroll version 16 

```
  node_modules/ngx-infinite-scroll/src/modules/ngx-infinite-scroll.module.d.ts:1:22
    1 export declare class InfiniteScrollModule {
                           ~~~~~~~~~~~~~~~~~~~~
    This likely means that the library (ngx-infinite-scroll) which declares InfiniteScrollModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
```

**Comment by orizens** [comment]
@MarcosPaulo775 would you mind checking that?

**Comment by orizens** [comment]
@beligh-hamdi can you review the pr again?

**Comment by MarcosPaulo775** [comment]
> @MarcosPaulo775 would you mind checking that?

I will check

**Comment by MarcosPaulo775** [comment]
> Angular/nfiniteScroll version 16
> 
> ```
>   node_modules/ngx-infinite-scroll/src/modules/ngx-infinite-scroll.module.d.ts:1:22
>     1 export declare class InfiniteScrollModule {
>                            ~~~~~~~~~~~~~~~~~~~~
>     This likely means that the library (ngx-infinite-scroll) which declares InfiniteScrollModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
> ```

Try this: https://github.com/angular/angular/issues/40616#issue-796138098

**Comment by MarcosPaulo775** [comment]
can close this issue ?
