### ISSUE TITLE
Scroll events not fired  with angular 16

### ISSUE THREAD

**Issue by belgacemfaycel** [orizens/ngx-infinite-scroll#424]
Scroll events not fired  with angular 16

I am testing ngrx-infinite-scroll( version 15/16) with angular 16 . but the scroll event does not fire .

Here is my script:

![image](https://github.com/orizens/ngx-infinite-scroll/assets/13342225/c325d06a-6f8c-42c5-99d1-b43edab03c98)

The same example works fine with angular 15

**Comment by DarioVincenzoDeSimone** [comment]
Same problem with Angular 16

**Comment by belgacemfaycel** [comment]
For me the problem was because of the css property overflow-y: scroll;
