### ISSUE TITLE
Trigger event of no scrollbar is present

### ISSUE THREAD

**Issue by angelaki** [orizens/ngx-infinite-scroll#428]
I'm facing a scenario, where my initially loaded items (on a pretty huge screen) are not enough to show a scrollbar. In my opinion it would be great, if the directive would fire a event here too (if `immediateCheck` is set to `true`).

What do you think? I'd offer a PR, if interessted.

**Comment by angelaki** [comment]
Just saw that this behavior actually isn't implemented (https://github.com/orizens/ngx-infinite-scroll/issues/341). Is there any reason? Could do that, too.

**Comment by ravindUwU** [comment]
As an interim solution, I added some "padding" to the bottom of the scrollable parent to ensure that the container stays scrollable. Pinging #341 .

Demo: https://stackblitz.com/edit/ravinduwu-ngx-infinite-scroll-parent-taller-than-items?file=src%2Fapp.component.html
