### ISSUE TITLE
Upgrade to Angular 17 ?

### ISSUE THREAD

**Issue by medbenmakhlouf** [orizens/ngx-infinite-scroll#429]
Is there any release plan for Angular 17? Thanks

**Comment by saheemshafi** [comment]
I want to know too. I was trying to upgrade my app from v16 to v17 and coudn't progess because of ngx-infinite-scroll version. Any updates?

**Comment by alecwest** [comment]
@medbenmakhlouf @saheemshafi based on previous upgrade issues (https://github.com/orizens/ngx-infinite-scroll/pull/419, https://github.com/orizens/ngx-infinite-scroll/issues/412, etc), it sounds as if anyone is welcome to contribute. 

If no one else beats me to it I'd like to give it a try.

**Comment by saheemshafi** [comment]
> @medbenmakhlouf @saheemshafi based on previous upgrade issues (#419, #412, etc), it sounds as if anyone is welcome to contribute.
> 
> If no one else beats me to it I'd like to give it a try.

If you want to start you can. I can't start soon and I won't start if you would.

**Comment by medbenmakhlouf** [comment]
I have opened a PR here : https://github.com/orizens/ngx-infinite-scroll/pull/430 

@orizens , would you mind to take a look please ? 

Thanks

**Comment by alecwest** [comment]
> I have opened a PR here : #430
> 
> @orizens , would you mind to take a look please ?
> 
> Thanks

thanks for starting that. It was probably going to be another day before I could properly get to it as well. 😄

**Comment by saheemshafi** [comment]
> I have opened a PR here : #430
> 
> @orizens , would you mind to take a look please ?
> 
> Thanks

I will have a look. Thanks for starting that. Will let you know about it shortly.

**Comment by orizens** [comment]
thanks @medbenmakhlouf reviewing

**Comment by medbenmakhlouf** [comment]
closing the issue as it was merged : https://github.com/orizens/ngx-infinite-scroll/pull/430
