### ISSUE TITLE
Angular 18 support for ngx-infinite-scroll 

### ISSUE THREAD

**Issue by shivarajnaidu** [orizens/ngx-infinite-scroll#435]
Angular 18 stable version has been released couple of days back..
https://blog.angular.dev/angular-v18-is-now-available-e79d5ac0affe

and need to bump ng-infinite-scroll deps to 18 !

Any plans ?

**Comment by mauriziocescon** [comment]
Done!

**Comment by orizens** [comment]
closed with #436
