### ISSUE TITLE
InfiniteScrollModule is deprecated ? angular 18, ngx-infinite-scroll 18

### ISSUE THREAD

**Issue by Trinita75** [orizens/ngx-infinite-scroll#438]
In visual studio code, in my angular 18 project, in app.module.ts import { InfiniteScrollModule } from 'ngx-infinite-scroll'; is reported as deprecated. I'm using angula 18.0.1 and ngx-infinite-scrol 18.0.0., am I doing something wrong?

**Comment by orizens** [comment]
you can still use - it's just a warning that the module will be removed in later versions.
start using the standalone version.

**Comment by HarelM** [comment]
I would advise to add a comment on how to replace it, as it is not clear how one should handle this deprecation...
Should I be importing the directive instead of the module now?

**Comment by orizens** [comment]
an example is available in
https://github.com/orizens/ngx-infinite-scroll/blob/master/README.md#usage

**Comment by HarelM** [comment]
Thanks! I meant adding this explanation to the doc comment of the deprecated module will allow users that see this scratched line in the IDE to easily see what they should do using tooltip.
