### ISSUE TITLE
ScrollDown event not fired on ctrl+end

### ISSUE THREAD

**Issue by brainsiq** [orizens/ngx-infinite-scroll#67]
If you scroll using the ctrl+end shortcut, or drag the scroll bar to the bottom of the page in one go the ScrollDown event doesn't fire. This seems to be due to the change in #58. Throttle fires the initial event to your handler function, which decides not to fire ScrollDown because of the scroll position, and then no further scroll events are raised so the handler does not run again.

Could possibly solve this by adding configuration to decide to use throttle or debounce?

CC @scooper91

**Comment by orizens** [comment]
hi @brainsiq 
i'm on mac -> cmd + end triggers the scroll method.

**Comment by brainsiq** [comment]
I'm on ubuntu with chrome and firefox. It fires the scroll method straight away but it's too soon as the scroll position hasn't updated yet.

**Comment by DethAriel** [comment]
Same behavior on Windows 10 here.

But I would make the problem more generic - if you reach the bottom of scroll area fast enough, the event is not fired and the content is not updated. Reproducible in this [plunk](https://plnkr.co/edit/QnQOwE9SEapwJCCFII3L?p=preview) - just scroll the modal fast

**Comment by prabhap** [comment]
Same behaviour on Mac too. The scroll method does not get fired when the scroll bar hits the bottom of the page. Please fix this bug asap.

**Comment by orizens** [comment]
hi @brainsiq 
after few attempts - i came to realize that the best solution would be to set "infiniteScrollThrottle" attribute to a small value - 10 worked with the demos quite good and didn't miss any scroll event.

**Comment by wadewalker25** [comment]
Hi, thanks for the project! 
I'm having the exact same issue as defined here, regardless of how low a value I set for 'infiniteScrollThrottle'. I've tried all various combinations of page size, scrollThrottle, scrollDistance, etc. It seems I can ALWAYS get to a point where the scroll bar will make it to the bottom when using the mouse wheel. However, I will say that holding page down or ctrl+end seems to always work. So I definitely think it's something to do with the mouse listener event.

**Comment by kunshao-msft** [comment]
This is still an issue for me. I am at version 0.3.1 and my parameter settings look like this:

<div class="scroll-results" infinite-scroll [infiniteScrollDistance]="1" [infiniteScrollThrottle]="10" (scrolled)="onScrollDown()" >

**Comment by orizens** [comment]
@brainsiq , @kunshao-msft , @wadewalker25 
does this still happen with v0.5.1?

**Comment by orizens** [comment]
hi
can you please check with latest beta (0.6.0) ?

**Comment by orizens** [comment]
hi @brainsiq can you please check with latest 0.7.0?

**Comment by blakeinate** [comment]
I am still having this issue at the latest version. I am on Ubuntu 18.04.1 running Chrome. I am also having an issue reported elsewhere in which the scrollup event is not triggered unless infiniteScrollUpDistance is above 7 and even then it is not consistently triggered when using page up or home.

**Comment by varuog** [comment]
I am having the same issue on Ubuntu 16 running chrome. when using infinity scroll in container, it does not fire scroll event anymore even for once, once it reaches the bottom of the container.

**Comment by madmacc** [comment]
I also have the same issue using v9.0.0.  When scrolling up if I scroll to the very top of the scrollbar by using the mouse on the scrollbar it loads the new data but does not retain the position in the element so it stays at the top of the scroll and then appears to jump up to the end of the new data.
You then can't scroll up any more unless you scroll down then back up again.

It works fine if you scroll up slowly.

**Comment by krishnanandsivaraj** [comment]
I do face the same problem still.  If I scroll slow it works like a charm but when we scroll fast it becomes unresponsive.  Not sure if that is a browser problem or the problem with this npm.  If we can fix this it will be good.
