### ISSUE TITLE
Suggestion: Infinite scroll block scrolling up

### ISSUE THREAD

**Issue by Perezmarc** [orizens/ngx-infinite-scroll#76]
When I load new ellements with scroll up, the scroll is set to top, and then, the new elements are shown and I lose reference of the element I was watching at the moment the new elements loaded.

Would be awesome to have an option to mantain scroll position in order to keep seeing the '0' element when '-1', '-2' are loaded.

status pre load:

0 --> on screen
1
2

status after load:

-2 --> on screen
-1
0
1
2

status after load desired: 

-2
-1
0 --> on screen
1
2

**Comment by orizens** [comment]
hi @Perezmarc 
let me know if i understood correctly: 
you want to be able to prevent the user from scrolling up?

**Comment by Perezmarc** [comment]
Nope, I want to prevent the screen, after load the new elements, to go up to -2 element, to stick with the element 0 that was the top of the screen before loading the elements. 

The user has 0 1 2 loaded, and if he scrolls up, he will be seeing the element 0, and because he scrolled up, we trigger the function to load elements before 0, when that's done, as the scroll position was top, it is still top, but now, we have -2 and -1 before the element 0, the one we were looking at. Therefore, we loaded new elements, but those are not seen until we scroll up again, having loaded the elements.

In fact, what I want is exactly the same behavior as scrolling down. I am in position 2, and after elements 3 4 are loaded, I'm in the same position I was before they load, position 2, but now I can scroll down to view the elements 3 and 4.

I hope I made my self clear now :)

**Comment by orizens** [comment]
@Perezmarc 
 I think i understood....
to solve this, I see it as a matter of logics that can be applied to the array of the rendered list in response to the relevant event. I think you can apply this logic by listening to the scrollUp/scrollDown event. However, it sounds complicated :) 
I'm not sure this kind of logics should be a part of this directive though.

**Comment by Perezmarc** [comment]
I believe it's a matter of scrolling, not array... the scroll position goes from top to bottom, if it is in 0 position (top), after load -2 -1 , it will still be in scroll 0, but now, it will be showing -2 element. 

Resolving this in array... would be weird, I think that if people want to use scrollup function to load elements they will all end up with this issue.

Thanks anyway, I'll try to implement it through array manipulation

**Comment by lxschmidt** [comment]
I am having the same issue. I have updated the example plunkr, to demonstarte the issue.

https://plnkr.co/edit/n7iqb2Ugv6tQv1DF2SX2?p=preview

When scrolling up, I am basically adding the items to the array, by using the unshift command.

[0, 1, 2]
array.unshift(-1)
[-1, 0, 1, 2]
array.unshift(-2)
[-2, 0, 1, 2]
etc.

It looks like when you do it like this, the scroll jumps automatically to the first element in the array. I am not sure if this is related to this module or the the implementation of ngFor.

**Comment by timschutter** [comment]
Suggested fix: (angular2-infinite-scroll   lines 89-106)
        InfiniteScroll.prototype.onScrollDown = function (data) {
            var _this = this;
            if (data === void 0) {
                data = { currentScrollPosition: 0 };
            }
            this.zone.run(function () {
                return _this.scrolled.emit(data);
            });
        };
        InfiniteScroll.prototype.onScrollUp = function (data) {
            var _this = this;
            if (data === void 0) {
                data = { currentScrollPosition: 0 };
            }
            this.zone.run(function () {
                return _this.scrolledUp.emit(data);
            });
        };
When scrolling down, I believe currentScrollPosition (for instance might be) 80 of 100.  Then new data is added, now currentScrollPosition is 80 of 120.  The scroll bar is placed in the right position.
When scrolling up, currentScrollPostion might be 20 of 100.  Then new data is added, and current ScrollPosition is still 20 of 120 when it should be 40 of 120 to maintain it's position.
Note:  I added this comment into item #114 as well.

**Comment by timschutter** [comment]
I was not liking the action of my down scroll so I changed the 'scroll distance' from 2 to 3.  When I did this, the up scroll started working as it is supposed to.  This was a big win for me because I had nightmares of how I was going to fix it.  Try this adjustment to see if it will help your scrolling up.
Thanks

**Comment by mackelito** [comment]
Is there any updates on this issue?

**Comment by orizens** [comment]
@mackelito not on the lib side.

**Comment by orizens** [comment]
@Perezmarc this lib now supports scroll up - please try again (you may look at the /example directory).
please reopen if this issue is different - or rather open an new issue linked to this one.
