### ISSUE TITLE
Can you bring back infiniteScrollContainer option?

### ISSUE THREAD

**Issue by kukiel** [orizens/ngx-infinite-scroll#97]
As in title - this option is very useful in some cases. Can you implement it in angular2 version?

**Comment by orizens** [comment]
can you provide a link?

**Comment by kukiel** [comment]
@orizens what link? I am talking about **infinite-scroll-container** parameter that was implemented in infinite-scroll directive for angular 1.x - http://sroze.github.io/ngInfiniteScroll/documentation.html. It would be awesome to have it also in your plugin (to have a possibility to track scroll not only based on window/current element).

**Comment by orizens** [comment]
isn't that the same container as the one you define the 'infinite-scroll' to?

**Comment by kukiel** [comment]
No, in some cases I want to track scroll of some parent element instead of the element that I defined infinite-scroll to. Also window scroll is not working as there is no window scroll at all in that case.

**Comment by orizens** [comment]
that seems out of scope for this directive, as you can use the [@Hostlistener()](https://angular.io/docs/ts/latest/api/core/index/HostListener-interface.html) and some kind of state
